const enc=new TextEncoder();
export function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}})}
export function bytesToHex(bytes){return [...bytes].map(b=>b.toString(16).padStart(2,'0')).join('')}
export async function sha256Hex(value){const d=await crypto.subtle.digest('SHA-256',enc.encode(value));return bytesToHex(new Uint8Array(d))}
export function getCookie(request,name){const raw=request.headers.get('cookie')||'';for(const p of raw.split(';')){const [k,...rest]=p.trim().split('=');if(k===name)return rest.join('=')}return ''}
export async function hashPassword(password){const salt=crypto.getRandomValues(new Uint8Array(16));const iterations=100000;const material=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations},material,256);return `pbkdf2_sha256$${iterations}$${bytesToHex(salt)}$${bytesToHex(new Uint8Array(bits))}`}
export async function verifyPassword(password,stored){try{const [algo,it,saltHex,hashHex]=String(stored||'').split('$');if(algo!=='pbkdf2_sha256')return false;const salt=new Uint8Array(saltHex.match(/.{1,2}/g).map(x=>parseInt(x,16)));const material=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations:Number(it)},material,256);return bytesToHex(new Uint8Array(bits))===hashHex}catch{return false}}
export async function ensureMemberSchema(DB){await DB.batch([
DB.prepare(`CREATE TABLE IF NOT EXISTS member_users (id INTEGER PRIMARY KEY AUTOINCREMENT, full_name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, institution TEXT, country TEXT DEFAULT 'Liberia', is_active INTEGER DEFAULT 1, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, last_login DATETIME)`),
DB.prepare(`CREATE TABLE IF NOT EXISTS member_sessions (id INTEGER PRIMARY KEY AUTOINCREMENT, member_user_id INTEGER NOT NULL, session_token_hash TEXT NOT NULL UNIQUE, expires_at DATETIME NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, last_used_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(member_user_id) REFERENCES member_users(id) ON DELETE CASCADE)`),
DB.prepare(`CREATE TABLE IF NOT EXISTS member_progress (id INTEGER PRIMARY KEY AUTOINCREMENT, member_user_id INTEGER NOT NULL, course_key TEXT NOT NULL, progress INTEGER DEFAULT 0, completed INTEGER DEFAULT 0, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE(member_user_id,course_key))`),
DB.prepare(`CREATE TABLE IF NOT EXISTS member_quiz_attempts (id INTEGER PRIMARY KEY AUTOINCREMENT, member_user_id INTEGER NOT NULL, quiz_key TEXT NOT NULL, score INTEGER NOT NULL, total INTEGER NOT NULL, attempted_at DATETIME DEFAULT CURRENT_TIMESTAMP)`)
])}
export async function currentMember(request,DB){await ensureMemberSchema(DB);const token=getCookie(request,'mtech_member_session');if(!token)return null;const hash=await sha256Hex(token);const row=await DB.prepare(`SELECT s.id session_id,u.id,u.full_name,u.email,u.institution,u.country FROM member_sessions s JOIN member_users u ON u.id=s.member_user_id WHERE s.session_token_hash=? AND s.expires_at>CURRENT_TIMESTAMP AND u.is_active=1 LIMIT 1`).bind(hash).first();if(row)await DB.prepare(`UPDATE member_sessions SET last_used_at=CURRENT_TIMESTAMP WHERE id=?`).bind(row.session_id).run();return row}
export function memberCookie(token,maxAge=1209600){return `mtech_member_session=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}`}
