const $=s=>document.querySelector(s);let state={user:null,done:new Set(),quiz:{},bookmarks:new Set(),certificates:[],subscription:null};
const lessons=[
{key:'computer-basics',icon:'💻',title:'Computer Basics',sub:'Hardware, files & operating systems',body:`<h2>Computer Basics</h2><p>A computer combines <b>hardware</b> (physical parts) and <b>software</b> (instructions/programs).</p><ul><li><b>CPU:</b> processes instructions.</li><li><b>RAM:</b> temporary working memory.</li><li><b>Storage:</b> SSD/HDD keeps files after power is off.</li><li><b>Operating system:</b> Windows, macOS or Linux manages hardware and apps.</li><li><b>Good habit:</b> organize files and keep backups.</li></ul><p><b>Practice:</b> identify the CPU, RAM, storage and operating system on a computer you use.</p>`},
{key:'office-productivity',icon:'📊',title:'Office & Productivity',sub:'Word, Excel & PowerPoint foundations',body:`<h2>Office & Productivity</h2><p>Productivity software helps you communicate and organize information.</p><ul><li><b>Word:</b> letters, reports and formatted documents.</li><li><b>Excel:</b> tables, calculations, lists and analysis.</li><li><b>PowerPoint:</b> visual presentations.</li><li>Use clear file names and folders.</li><li>Save frequently and keep a backup copy.</li></ul><p><b>Practice:</b> create a one-page CV, a five-row budget sheet and a three-slide presentation.</p>`},
{key:'internet-safety',icon:'🛡️',title:'Internet & Cyber Safety',sub:'Passwords, phishing & safer browsing',body:`<h2>Internet & Cyber Safety</h2><p>Security begins with everyday habits.</p><ul><li>Use long, unique passwords for important accounts.</li><li>Turn on multi-factor authentication when available.</li><li>Do not trust urgent messages asking for passwords or money.</li><li>Check the sender and website before entering credentials.</li><li>Install updates and back up important data.</li></ul><p><b>Remember:</b> legitimate support should not need your password.</p>`},
{key:'networking',icon:'🌐',title:'Networking Basics',sub:'Wi-Fi, routers, IP addresses & LANs',body:`<h2>Networking Basics</h2><p>A network allows devices to communicate.</p><ul><li><b>Router:</b> connects networks and commonly shares internet access.</li><li><b>Switch:</b> connects devices within a local network.</li><li><b>IP address:</b> identifies a device/interface on an IP network.</li><li><b>Wi-Fi:</b> wireless local networking technology.</li><li><b>Ethernet:</b> common wired networking technology.</li></ul><p><b>Practice:</b> locate your router and identify devices connected by Wi-Fi and cable.</p>`},
{key:'hardware-repair',icon:'🔧',title:'Hardware & Troubleshooting',sub:'Safe diagnosis and maintenance',body:`<h2>Hardware & Troubleshooting</h2><p>Good troubleshooting is systematic, not guesswork.</p><ol><li>Ask what changed and record the symptoms.</li><li>Check power, cables and obvious physical issues.</li><li>Back up important data before risky changes.</li><li>Test one likely cause at a time.</li><li>Document what fixed the problem.</li></ol><p>For electrical or battery damage, use qualified service procedures and appropriate safety precautions.</p>`},
{key:'web-coding',icon:'⌨️',title:'Web & Coding Foundations',sub:'HTML, CSS & JavaScript concepts',body:`<h2>Web & Coding Foundations</h2><p>Most interactive websites combine three core technologies.</p><ul><li><b>HTML</b> gives a page its structure and meaning.</li><li><b>CSS</b> controls presentation and responsive layout.</li><li><b>JavaScript</b> adds behavior and interactivity.</li></ul><p><b>Practice idea:</b> HTML creates a button, CSS styles it, and JavaScript decides what happens when it is clicked.</p>`}
];
const quizzes=[{key:'computer',title:'Computer Basics Quiz',qs:[['Which component is temporary working memory?',['SSD','RAM','Monitor'],1],['Which keeps files when power is off?',['Storage','RAM','CPU cache only'],0],['Windows is primarily a…',['Cable','Operating system','Router'],1]]},{key:'safety',title:'Cyber Safety Quiz',qs:[['Best password practice?',['Reuse one password','Use unique strong passwords','Share passwords'],1],['A suspicious urgent login link may be…',['Phishing','RAM','Ethernet'],0],['Extra account protection?',['Disable updates','Multi-factor authentication','Public password'],1]]},{key:'network',title:'Networking Quiz',qs:[['Device commonly connecting your LAN to internet?',['Router','Keyboard','Printer'],0],['Wi-Fi is mainly…',['Wireless networking','Storage','A file type'],0],['An IP address helps…',['Identify a network interface','Charge a battery','Print paper'],0]]}];
async function api(action,method='GET',body){let r=await fetch('/api/member?action='+action,{method,headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined});let d=await r.json().catch(()=>({ok:false,error:'Unexpected server response.'}));if(!r.ok)throw new Error(d.error||'Request failed');return d}
function msg(t,bad=false){let e=$('#authMsg');e.textContent=t;e.style.color=bad?'#ff8e9b':'#62d9ff'}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));$('#loginForm').classList.toggle('hidden',b.dataset.tab!=='login');$('#registerForm').classList.toggle('hidden',b.dataset.tab!=='register');msg('')});
$('#registerForm').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target);try{let d=await api('register','POST',{fullName:f.get('fullName'),email:f.get('email'),password:f.get('password')});msg(d.message);e.target.reset();document.querySelector('[data-tab=login]').click()}catch(x){msg(x.message,true)}};
$('#loginForm').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target);try{await api('login','POST',{email:f.get('email'),password:f.get('password')});await load()}catch(x){msg(x.message,true)}};
$('#logout').onclick=async()=>{await api('logout','POST').catch(()=>{});state={user:null,done:new Set(),quiz:{},bookmarks:new Set(),certificates:[],subscription:null};showAuth()};
$('#courseSearch').oninput=renderCourses;
function showAuth(){$('#auth').classList.remove('hidden');$('#dashboard').classList.add('hidden');$('#logout').classList.add('hidden')}
function renderCourses(){let term=($('#courseSearch')?.value||'').toLowerCase();let list=lessons.filter(l=>(l.title+' '+l.sub).toLowerCase().includes(term));$('#categories').innerHTML=list.map(l=>`<article><div class="card-top"><span class="icon">${l.icon}</span><button class="bookmark ${state.bookmarks.has(l.key)?'saved':''}" onclick="toggleBookmark('${l.key}')" title="Save lesson">${state.bookmarks.has(l.key)?'★':'☆'}</button></div><h3>${l.title}</h3><p>${l.sub}</p><small>${state.done.has(l.key)?'✓ Starter lesson completed':'Starter lesson • Free'}</small><button class="lesson-btn" onclick="openLesson('${l.key}')">${state.done.has(l.key)?'Review lesson':'Start lesson'}</button></article>`).join('')||'<p>No lessons match your search.</p>'}
function render(){ $('#auth').classList.add('hidden');$('#dashboard').classList.remove('hidden');$('#logout').classList.remove('hidden');$('#welcome').textContent=`Welcome, ${state.user.fullName.split(' ')[0]}.`;renderCourses();$('#quizzes').innerHTML=quizzes.map(q=>{let info=state.quiz[q.key],passed=info&&info.best_score*100>=info.total*67;return `<article><h3>${q.title}</h3><p>3 questions • instant result</p><small>${info?`Best: ${info.best_score}/${info.total} • ${info.attempts||1} attempt(s)`:'Not attempted yet'}</small><span class="pill ${passed?'active':''}">${passed?'Passed':'Need 67%'}</span><button onclick="openQuiz('${q.key}')">${info?'Try again':'Take quiz'}</button></article>`}).join('');let lessonPct=Math.round(state.done.size/lessons.length*100),passedCount=quizzes.filter(q=>{let i=state.quiz[q.key];return i&&i.best_score*100>=i.total*67}).length,pct=Math.round((state.done.size+passedCount)/(lessons.length+quizzes.length)*100);$('#progressPct').textContent=pct+'%';$('#progressBar').style.width=pct+'%';$('#lessonStat').textContent=`${state.done.size}/${lessons.length}`;$('#quizStat').textContent=`${passedCount}/${quizzes.length}`;$('#bookmarkStat').textContent=state.bookmarks.size;$('#certStat').textContent=state.certificates.length;$('#lessonBadge').textContent=state.done.size===lessons.length?'Completed ✓':'In progress';$('#lessonBadge').classList.toggle('active',state.done.size===lessons.length);$('#quizBadge').textContent=passedCount===quizzes.length?'Completed ✓':'In progress';$('#quizBadge').classList.toggle('active',passedCount===quizzes.length);$('#planBadge').textContent=(state.subscription?.status==='active'&&state.subscription?.plan_code!=='free')?'Premium Member':'Free Member';renderCertificate()}
async function load(){try{let d=await api('session');state.user=d.user;state.done=new Set((d.progress||[]).filter(x=>x.completed).map(x=>x.item_key));state.quiz=Object.fromEntries((d.quizzes||[]).map(x=>[x.quiz_key,x]));state.bookmarks=new Set((d.bookmarks||[]).map(x=>x.item_key));state.certificates=d.certificates||[];state.subscription=d.subscription||null;render()}catch{showAuth()}}
window.openLesson=k=>{let l=lessons.find(x=>x.key===k);$('#lessonContent').innerHTML=`<div class="lesson-body">${l.body}<div class="lesson-actions"><button class="ghost" onclick="toggleBookmark('${k}')">${state.bookmarks.has(k)?'★ Saved':'☆ Save lesson'}</button><button class="primary" onclick="completeLesson('${k}')">${state.done.has(k)?'Completed ✓':'Mark lesson complete'}</button></div></div>`;lessonDialog.showModal()};
window.completeLesson=async k=>{try{await api('progress','POST',{itemKey:k});state.done.add(k);lessonDialog.close();render()}catch(e){alert(e.message)}};
window.toggleBookmark=async k=>{try{let d=await api('bookmark','POST',{itemKey:k});d.bookmarked?state.bookmarks.add(k):state.bookmarks.delete(k);render();if(lessonDialog.open)openLesson(k)}catch(e){alert(e.message)}};
window.openQuiz=k=>{let q=quizzes.find(x=>x.key===k);$('#quizContent').innerHTML=`<h2>${q.title}</h2><form id="activeQuiz">${q.qs.map((x,i)=>`<div class="q"><b>${i+1}. ${x[0]}</b>${x[1].map((a,j)=>`<label><input type="radio" name="q${i}" value="${j}" required> ${a}</label>`).join('')}</div>`).join('')}<button class="primary" style="margin-top:18px">Submit quiz</button></form><p id="quizResult"></p>`;$('#activeQuiz').onsubmit=e=>submitQuiz(e,k);quizDialog.showModal()};
async function submitQuiz(e,k){e.preventDefault();let q=quizzes.find(x=>x.key===k),f=new FormData(e.target),score=q.qs.reduce((n,x,i)=>n+(+f.get('q'+i)===x[2]),0);try{await api('quiz','POST',{quizKey:k,score,total:q.qs.length});$('#quizResult').textContent=`Score: ${score}/${q.qs.length} — ${score===q.qs.length?'Excellent!':score>=2?'Passed! Review any missed topic.':'Keep learning and try again.'}`;let old=state.quiz[k];state.quiz[k]={best_score:Math.max(score,old?.best_score||0),total:q.qs.length,attempts:(old?.attempts||0)+1};render()}catch(x){$('#quizResult').textContent=x.message}}
function renderCertificate(){let a=$('#certificateArea');if(!a)return;let c=state.certificates[0];a.innerHTML=c?`<div class="cert-card"><b>${c.title}</b><span>${c.certificate_code}</span><small>Issued ${new Date(c.issued_at).toLocaleDateString()}</small><button onclick="printCertificate('${c.certificate_code}')">Print certificate</button></div>`:''}
window.issueCertificate=async()=>{try{let d=await api('certificate','POST');if(!state.certificates.some(c=>c.certificate_code===d.certificate.certificate_code))state.certificates.unshift(d.certificate);render()}catch(e){alert(e.message)}};
window.printCertificate=code=>{let c=state.certificates.find(x=>x.certificate_code===code);if(!c)return;let w=window.open('','_blank');w.document.write(`<html><head><title>${c.title}</title><style>body{font-family:Arial;text-align:center;padding:60px;border:18px double #123b75}h1{font-size:42px}h2{font-size:30px}.code{margin-top:40px;font-family:monospace}</style></head><body><h3>M-TECH — Mulbah Technology Solution Liberia Ltd.</h3><h1>Certificate of Completion</h1><p>This certifies that</p><h2>${state.user.fullName}</h2><p>has successfully completed</p><h2>${c.title}</h2><p>${c.score_summary||''}</p><div class="code">Certificate: ${c.certificate_code}<br>Issued: ${new Date(c.issued_at).toLocaleDateString()}</div></body></html>`);w.document.close();w.print()};
window.convertStorage=()=>{$('#storageOut').textContent=(+$('#gb').value*1024).toLocaleString()+' MB'};
window.downloadTime=()=>{let mb=+$('#fileMb').value,s=+$('#speed').value;if(!mb||!s)return $('#timeOut').textContent='Enter valid values.';let sec=mb*8/s;$('#timeOut').textContent=sec<60?`${sec.toFixed(1)} seconds`:`${(sec/60).toFixed(1)} minutes (approx.)`};
window.passwordCheck=()=>{let p=$('#pwcheck').value,n=0;n+=p.length>=12;n+=/[A-Z]/.test(p)&&/[a-z]/.test(p);n+=/\d/.test(p);n+=/[^\w]/.test(p);$('#pwOut').textContent=['Very weak','Weak','Fair','Good','Strong'][n]};
window.binaryConvert=()=>{let n=+$('#decimalInput').value;$('#binaryOut').textContent=Number.isInteger(n)&&n>=0?n.toString(2):'Enter a whole number.'};
window.typingCheck=()=>{let target='Technology builds opportunity.',typed=$('#typingInput').value;let same=[...target].filter((c,i)=>typed[i]===c).length;$('#typingOut').textContent=`Accuracy: ${Math.round(same/target.length*100)}%`};
window.scrollToSection=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'});
window.openPayment=plan=>{$('#paymentForm [name=planCode]').value=plan;$('#paymentMsg').textContent='';paymentDialog.showModal()};
$('#paymentForm').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target);try{let d=await api('payment-request','POST',{provider:f.get('provider'),planCode:f.get('planCode'),phone:f.get('phone')});$('#paymentMsg').textContent=`Pending request ${d.reference} for LRD ${d.amountLrd.toLocaleString()}. ${d.message}`;e.target.reset()}catch(x){$('#paymentMsg').textContent=x.message}};
window.verifyCertificate=async()=>{let code=$('#verifyCode').value.trim();if(!code)return $('#verifyOut').textContent='Enter a certificate code.';try{let r=await fetch('/api/certificate?code='+encodeURIComponent(code)),d=await r.json();if(!r.ok)throw new Error(d.error||'Not found');$('#verifyOut').textContent=`VALID ✓ ${d.certificate.learner} — ${d.certificate.title} — issued ${new Date(d.certificate.issuedAt).toLocaleDateString()}`;}catch(e){$('#verifyOut').textContent='Not verified: '+e.message}};
if(new URLSearchParams(location.search).get('mode')==='register')document.querySelector('[data-tab=register]')?.click();load();