const $=s=>document.querySelector(s);let state={user:null,done:new Set(),quiz:{}};
const lessons=[
{key:'computer-basics',icon:'💻',title:'Computer Basics',sub:'Hardware, files & operating systems',body:`<h2>Computer Basics</h2><p>A computer combines <b>hardware</b> (physical parts) and <b>software</b> (instructions/programs).</p><ul><li><b>CPU:</b> processes instructions.</li><li><b>RAM:</b> temporary working memory.</li><li><b>Storage:</b> SSD/HDD keeps files after power is off.</li><li><b>Operating system:</b> Windows, macOS or Linux manages hardware and apps.</li><li><b>Good habit:</b> keep important files organized and backed up.</li></ul><p>Practice: identify the CPU, RAM, storage and operating system on a computer you use.</p>`},
{key:'office-productivity',icon:'📊',title:'Office & Productivity',sub:'Word, Excel & PowerPoint foundations',body:`<h2>Office & Productivity</h2><p>Productivity software helps you communicate and organize information.</p><ul><li><b>Word:</b> letters, reports and formatted documents.</li><li><b>Excel:</b> tables, calculations, lists and analysis.</li><li><b>PowerPoint:</b> visual presentations.</li><li>Use clear file names and folders.</li><li>Save frequently and keep a backup copy.</li></ul><p>Practice: create a one-page CV, a five-row budget sheet, and a three-slide presentation.</p>`},
{key:'internet-safety',icon:'🛡️',title:'Internet & Cyber Safety',sub:'Passwords, phishing & safer browsing',body:`<h2>Internet & Cyber Safety</h2><p>Security begins with everyday habits.</p><ul><li>Use long, unique passwords for important accounts.</li><li>Turn on multi-factor authentication when available.</li><li>Do not trust urgent messages asking for passwords or money.</li><li>Check the sender and website before entering credentials.</li><li>Install updates and back up important data.</li></ul><p>Remember: legitimate support should not need your password.</p>`},
{key:'networking',icon:'🌐',title:'Networking Basics',sub:'Wi-Fi, routers, IP addresses & LANs',body:`<h2>Networking Basics</h2><p>A network allows devices to communicate.</p><ul><li><b>Router:</b> connects networks and commonly shares internet access.</li><li><b>Switch:</b> connects devices within a local network.</li><li><b>IP address:</b> identifies a device/interface on an IP network.</li><li><b>Wi-Fi:</b> wireless local networking technology.</li><li><b>Ethernet:</b> common wired networking technology.</li></ul><p>Practice: locate your router and identify which devices connect by Wi-Fi and which by cable.</p>`},
{key:'hardware-repair',icon:'🔧',title:'Hardware & Troubleshooting',sub:'Safe diagnosis and maintenance',body:`<h2>Hardware & Troubleshooting</h2><p>Good troubleshooting is systematic, not guesswork.</p><ol><li>Ask what changed and record the symptoms.</li><li>Check power, cables and obvious physical issues.</li><li>Back up important data before risky changes.</li><li>Test one likely cause at a time.</li><li>Document what fixed the problem.</li></ol><p>For electrical or battery damage, use qualified service procedures and appropriate safety precautions.</p>`},
{key:'web-coding',icon:'⌨️',title:'Web & Coding Foundations',sub:'HTML, CSS & JavaScript concepts',body:`<h2>Web & Coding Foundations</h2><p>Most interactive websites combine three core technologies.</p><ul><li><b>HTML</b> gives a page its structure and meaning.</li><li><b>CSS</b> controls presentation and responsive layout.</li><li><b>JavaScript</b> adds behavior and interactivity.</li></ul><p>Example idea: HTML creates a button, CSS styles it, and JavaScript decides what happens when it is clicked.</p>`}
];
const quizzes=[{key:'computer',title:'Computer Basics Quiz',qs:[['Which component is temporary working memory?',['SSD','RAM','Monitor'],1],['Which keeps files when power is off?',['Storage','RAM','CPU cache only'],0],['Windows is primarily a…',['Cable','Operating system','Router'],1]]},{key:'safety',title:'Cyber Safety Quiz',qs:[['Best password practice?',['Reuse one password','Use unique strong passwords','Share passwords'],1],['A suspicious urgent login link may be…',['Phishing','RAM','Ethernet'],0],['Extra account protection?',['Disable updates','Multi-factor authentication','Public password'],1]]},{key:'network',title:'Networking Quiz',qs:[['Device commonly connecting your LAN to internet?',['Router','Keyboard','Printer'],0],['Wi-Fi is mainly…',['Wireless networking','Storage','A file type'],0],['An IP address helps…',['Identify a network interface','Charge a battery','Print paper'],0]]}];
async function api(action,method='GET',body){let r=await fetch('/api/member?action='+action,{method,headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined});let d=await r.json().catch(()=>({ok:false,error:'Unexpected server response.'}));if(!r.ok)throw new Error(d.error||'Request failed');return d}
function msg(t,bad=false){let e=$('#authMsg');e.textContent=t;e.style.color=bad?'#ff8e9b':'#62d9ff'}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));$('#loginForm').classList.toggle('hidden',b.dataset.tab!=='login');$('#registerForm').classList.toggle('hidden',b.dataset.tab!=='register');msg('')});
$('#registerForm').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target);try{let d=await api('register','POST',{fullName:f.get('fullName'),email:f.get('email'),password:f.get('password')});msg(d.message);e.target.reset();document.querySelector('[data-tab=login]').click()}catch(x){msg(x.message,true)}};
$('#loginForm').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target);try{await api('login','POST',{email:f.get('email'),password:f.get('password')});await load()}catch(x){msg(x.message,true)}};
$('#logout').onclick=async()=>{await api('logout','POST').catch(()=>{});state={user:null,done:new Set(),quiz:{}};showAuth()};
function showAuth(){$('#auth').classList.remove('hidden');$('#dashboard').classList.add('hidden');$('#logout').classList.add('hidden')}
function render(){ $('#auth').classList.add('hidden');$('#dashboard').classList.remove('hidden');$('#logout').classList.remove('hidden');$('#welcome').textContent=`Welcome, ${state.user.fullName.split(' ')[0]}.`;$('#categories').innerHTML=lessons.map(l=>`<article><span class="icon">${l.icon}</span><h3>${l.title}</h3><p>${l.sub}</p><small>${state.done.has(l.key)?'✓ Starter lesson completed':'Starter lesson • Free'}</small><button class="lesson-btn" onclick="openLesson('${l.key}')">${state.done.has(l.key)?'Review lesson':'Start lesson'}</button></article>`).join('');$('#quizzes').innerHTML=quizzes.map(q=>`<article><h3>${q.title}</h3><p>3 questions • instant result</p><small>${state.quiz[q.key]?`Best: ${state.quiz[q.key].best_score}/${state.quiz[q.key].total}`:'Not attempted yet'}</small><button onclick="openQuiz('${q.key}')">Take quiz</button></article>`).join('');let pct=Math.round(state.done.size/lessons.length*100);$('#progressPct').textContent=pct+'%';$('#progressBar').style.width=pct+'%'}
async function load(){try{let d=await api('session');state.user=d.user;state.done=new Set((d.progress||[]).filter(x=>x.completed).map(x=>x.item_key));state.quiz=Object.fromEntries((d.quizzes||[]).map(x=>[x.quiz_key,x]));render()}catch{showAuth()}}
window.openLesson=k=>{let l=lessons.find(x=>x.key===k);$('#lessonContent').innerHTML=`<div class="lesson-body">${l.body}<button class="primary" onclick="completeLesson('${k}')">${state.done.has(k)?'Completed ✓':'Mark lesson complete'}</button></div>`;lessonDialog.showModal()};
window.completeLesson=async k=>{try{await api('progress','POST',{itemKey:k});state.done.add(k);lessonDialog.close();render()}catch(e){alert(e.message)}};
window.openQuiz=k=>{let q=quizzes.find(x=>x.key===k);$('#quizContent').innerHTML=`<h2>${q.title}</h2><form id="activeQuiz">${q.qs.map((x,i)=>`<div class="q"><b>${i+1}. ${x[0]}</b>${x[1].map((a,j)=>`<label><input type="radio" name="q${i}" value="${j}" required> ${a}</label>`).join('')}</div>`).join('')}<button class="primary" style="margin-top:18px">Submit quiz</button></form><p id="quizResult"></p>`;$('#activeQuiz').onsubmit=e=>submitQuiz(e,k);quizDialog.showModal()};
async function submitQuiz(e,k){e.preventDefault();let q=quizzes.find(x=>x.key===k),f=new FormData(e.target),score=q.qs.reduce((n,x,i)=>n+(+f.get('q'+i)===x[2]),0);try{await api('quiz','POST',{quizKey:k,score,total:q.qs.length});$('#quizResult').textContent=`Score: ${score}/${q.qs.length} — ${score===q.qs.length?'Excellent!':score>=2?'Good work! Review any missed topic.':'Keep learning and try again.'}`;let old=state.quiz[k];state.quiz[k]={best_score:Math.max(score,old?.best_score||0),total:q.qs.length};render()}catch(x){$('#quizResult').textContent=x.message}}
window.convertStorage=()=>{$('#storageOut').textContent=(+$('#gb').value*1024).toLocaleString()+' MB'};
window.downloadTime=()=>{let mb=+$('#fileMb').value,s=+$('#speed').value;if(!mb||!s)return $('#timeOut').textContent='Enter valid values.';let sec=mb*8/s;$('#timeOut').textContent=sec<60?`${sec.toFixed(1)} seconds`:`${(sec/60).toFixed(1)} minutes (approx.)`};
window.passwordCheck=()=>{let p=$('#pwcheck').value,n=0;n+=p.length>=12;n+=/[A-Z]/.test(p)&&/[a-z]/.test(p);n+=/\d/.test(p);n+=/[^\w]/.test(p);$('#pwOut').textContent=['Very weak','Weak','Fair','Good','Strong'][n]};
load();