(()=>{'use strict';
const SB=supabase.createClient('https://vsirepejlaytbqhhikev.supabase.co','sb_publishable_vQULGJJZNtuT_MZCSqomiQ_URYS4BQp',{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let session=null,profile=null,categories=[],resources=[],bookmarks=[],progress=[],current=null;
function toast(t){const el=$('toast');el.textContent=t;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),2600)}
function fmtBytes(n){if(!n)return '';const u=['B','KB','MB','GB'];let i=0,x=Number(n);while(x>=1024&&i<u.length-1){x/=1024;i++}return `${x.toFixed(i?1:0)} ${u[i]}`}
function canUpload(){return String(profile?.role||'').toLowerCase()==='ceo'}
async function init(){const {data}=await SB.auth.getSession();session=data.session;if(!session){location.href='management.html';return}const {data:p}=await SB.from('profiles').select('*').eq('id',session.user.id).maybeSingle();profile=p;if(!p?.active){await SB.auth.signOut();location.href='management.html';return}if(canUpload())$('uploadBtn').classList.remove('hidden');bind();await loadAll()}
function bind(){$('search').addEventListener('input',render);$('category').addEventListener('change',render);$('level').addEventListener('change',render);$('uploadBtn').onclick=openUpload;$('readerClose').onclick=closeReader;$('readerSave').onclick=saveProgress;$('readerBookmark').onclick=addBookmark}
async function loadAll(){ $('status').textContent='Loading library…';const [{data:c},{data:r},{data:b},{data:p}]=await Promise.all([
SB.from('education_categories').select('*').order('sort_order'),
SB.from('education_resources').select('*,education_categories(name)').order('featured',{ascending:false}).order('created_at',{ascending:false}),
SB.from('education_bookmarks').select('*').eq('user_id',session.user.id),
SB.from('education_reading_progress').select('*').eq('user_id',session.user.id)
]);categories=c||[];resources=r||[];bookmarks=b||[];progress=p||[];$('category').innerHTML='<option value="">All Categories</option>'+categories.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');updateMetrics();render();}
function updateMetrics(){$('mResources').textContent=resources.length.toLocaleString();$('mPages').textContent=resources.reduce((a,x)=>a+Number(x.page_count||0),0).toLocaleString();$('mCategories').textContent=categories.length.toLocaleString();$('mBookmarks').textContent=bookmarks.length.toLocaleString()}
function render(){let a=[...resources],q=$('search').value.trim().toLowerCase(),cat=$('category').value,lvl=$('level').value;if(q)a=a.filter(x=>JSON.stringify([x.title,x.subtitle,x.description,x.author_source,x.publisher,x.tags,x.education_categories?.name]).toLowerCase().includes(q));if(cat)a=a.filter(x=>x.category_id===cat);if(lvl)a=a.filter(x=>x.level===lvl);$('status').textContent=`${a.length} resource${a.length===1?'':'s'}`;$('library').innerHTML=a.length?a.map(card).join(''):'<div class="card empty">No matching resources yet.</div>';document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openResource(b.dataset.open));}
function card(r){const pr=progress.find(x=>x.resource_id===r.id),pct=Number(pr?.percent_complete||0),bm=bookmarks.some(x=>x.resource_id===r.id);return `<article class="card resource"><div class="chips">${r.featured?'<span class="chip">Featured</span>':''}<span class="chip">${esc(r.education_categories?.name||'Uncategorized')}</span><span class="chip">${esc((r.level||'all').replace('_',' / '))}</span><span class="chip">${esc(r.access_level)}</span></div><h3>${esc(r.title)}</h3>${r.subtitle?`<div class="muted">${esc(r.subtitle)}</div>`:''}<div class="desc">${esc(r.description||'M-TECH educational resource')}</div><div class="muted">${esc(r.author_source||'M-TECH Library')}${r.page_count?` · ${r.page_count.toLocaleString()} pages`:''}${r.file_size_bytes?` · ${fmtBytes(r.file_size_bytes)}`:''}</div>${pr?`<div><div class="muted">Continue from page ${pr.current_page} · ${pct.toFixed(0)}%</div><div class="progress"><i style="width:${Math.max(0,Math.min(100,pct))}%"></i></div></div>`:''}<div class="actions"><button class="btn" data-open="${r.id}">${pr?'Continue Reading':'Open Resource'}</button>${bm?'<span class="chip">★ Bookmarked</span>':''}</div></article>`}
async function openResource(id){const r=resources.find(x=>x.id===id);if(!r)return;current=r;let url=r.external_url||'';if(r.storage_path){const {data,error}=await SB.storage.from('education-library').createSignedUrl(r.storage_path,3600);if(error){toast('Could not open this resource.');return}url=data?.signedUrl||''}if(!url){toast('No readable file is attached yet.');return}const pr=progress.find(x=>x.resource_id===r.id);$('readerTitle').textContent=r.title;$('readerPage').value=pr?.current_page||1;$('readerFrame').src=url;$('reader').classList.remove('hidden');await upsertProgress(Number($('readerPage').value||1),false)}
function closeReader(){$('reader').classList.add('hidden');$('readerFrame').src='';current=null;loadAll().catch(()=>{})}
async function upsertProgress(page,notify=true){if(!current)return;const total=Number(current.page_count||0),pct=total?Math.min(100,(page/total)*100):0;const row={user_id:session.user.id,resource_id:current.id,current_page:Math.max(1,page),percent_complete:pct,last_opened_at:new Date().toISOString(),completed_at:total&&page>=total?new Date().toISOString():null};const {error}=await SB.from('education_reading_progress').upsert(row,{onConflict:'user_id,resource_id'});if(!error&&notify)toast('Reading progress saved.');}
async function saveProgress(){await upsertProgress(Number($('readerPage').value||1),true)}
async function addBookmark(){if(!current)return;const page=Math.max(1,Number($('readerPage').value||1));const {error}=await SB.from('education_bookmarks').upsert({user_id:session.user.id,resource_id:current.id,page_number:page},{onConflict:'user_id,resource_id,page_number'});if(error)toast('Bookmark could not be saved.');else toast(`Bookmarked page ${page}.`)}
function openUpload(){if(!canUpload())return;const host=$('uploadModal');host.className='modal-back';host.innerHTML=`<div class="modal"><div class="section-title"><h2>CEO Resource Upload Center</h2><button class="btn alt" id="upClose">Close</button></div><div class="fields"><div class="field full"><label>PDF file (up to 500 MB)</label><input id="upFile" type="file" accept="application/pdf"></div><div class="field full"><label>Resource title</label><input id="upTitle" placeholder="Example: Advanced Computer Networking Handbook"></div><div class="field"><label>Category</label><select id="upCategory">${categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Learning level</label><select id="upLevel"><option value="all">All Levels</option><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option><option value="professional">Professional</option><option value="certification">Certification</option><option value="college_university">College / University</option><option value="research">Research</option></select></div><div class="field"><label>Access</label><select id="upAccess"><option value="registered">Approved M-TECH Users</option><option value="staff">Staff</option><option value="student">Students / Learners</option><option value="instructor">Instructor / Management</option><option value="ceo">CEO Only</option></select></div><div class="field"><label>Page count</label><input id="upPages" type="number" min="1" placeholder="500"></div><div class="field"><label>Author / source</label><input id="upAuthor"></div><div class="field"><label>Publication year</label><input id="upYear" type="number" min="1900" max="2100"></div><div class="field full"><label>Description</label><textarea id="upDescription" rows="4"></textarea></div><div class="field full"><label>Tags (comma separated)</label><input id="upTags" placeholder="networking, cisco, starlink, routing"></div><div class="field"><label><input id="upDownload" type="checkbox"> Allow download</label></div><div class="field"><label><input id="upPrint" type="checkbox"> Allow printing</label></div><div class="field"><label><input id="upFeatured" type="checkbox"> Featured resource</label></div><div class="field full"><div class="upload-progress"><span id="upBar"></span></div><div id="upMsg" class="muted"></div></div></div><div class="actions" style="margin-top:14px"><button id="upSave" class="btn">Upload & Add to Library</button></div></div>`;$('upClose').onclick=()=>{host.className='hidden';host.innerHTML=''};$('upSave').onclick=uploadResource}
async function uploadResource(){const f=$('upFile').files[0],title=$('upTitle').value.trim();if(!f||f.type!=='application/pdf'){toast('Choose a PDF file first.');return}if(!title){toast('Enter a resource title.');return}if(f.size>524288000){toast('This PDF is larger than the 500 MB limit.');return}const btn=$('upSave'),msg=$('upMsg'),bar=$('upBar');btn.disabled=true;msg.textContent='Uploading securely to M-TECH Education Library…';bar.style.width='20%';const safe=f.name.replace(/[^a-zA-Z0-9._-]+/g,'-');const path=`${session.user.id}/${Date.now()}-${safe}`;try{const {error:upErr}=await SB.storage.from('education-library').upload(path,f,{contentType:'application/pdf',upsert:false});if(upErr)throw upErr;bar.style.width='78%';const row={title,description:$('upDescription').value.trim()||null,category_id:$('upCategory').value||null,resource_type:'pdf',storage_path:path,author_source:$('upAuthor').value.trim()||null,publication_year:Number($('upYear').value)||null,page_count:Number($('upPages').value)||null,file_size_bytes:f.size,level:$('upLevel').value,access_level:$('upAccess').value,allow_download:$('upDownload').checked,allow_print:$('upPrint').checked,featured:$('upFeatured').checked,tags:$('upTags').value.split(',').map(x=>x.trim()).filter(Boolean),uploaded_by:session.user.id};const {error}=await SB.from('education_resources').insert(row);if(error){await SB.storage.from('education-library').remove([path]);throw error}bar.style.width='100%';msg.textContent='Resource uploaded successfully.';toast('Resource added to the M-TECH library.');setTimeout(()=>{$('uploadModal').className='hidden';$('uploadModal').innerHTML='';loadAll()},700)}catch(e){msg.textContent=e.message||'Upload failed.';bar.style.width='0';btn.disabled=false}}
init().catch(e=>{console.error(e);$('status').textContent='Education Center could not load.'});
})();