// M-TECH Expert Final Integration
(function(){
 const by=id=>document.getElementById(id),E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 function addOpsPanels(){const nav=by('nav'),content=document.querySelector('.content');if(!nav||!content||by('expertOps'))return;const b=document.createElement('button');b.className='navbtn';b.dataset.panel='expertOps';b.textContent='Technician & Job Profit';b.onclick=()=>{openPanel('expertOps','Technician & Job Profit');renderOps()};nav.appendChild(b);content.insertAdjacentHTML('beforeend',`<section id="expertOps" class="panel"><div class="section-title"><h2>Technician & Job Profitability</h2><button class="btn alt small" onclick="mtechRefreshOps()">Refresh</button></div><div id="opsJobs" class="table-wrap"></div></section>`)}
 async function renderOps(){const {data:users}=await SB.from('profiles').select('id,full_name,email,role,active').eq('active',true);const u=users||[];const rows=[];for(const j of state.jobs||[]){const {data:p}=await SB.rpc('job_profitability',{p_job_id:j.id});const tech=u.find(x=>x.id===j.assigned_user_id);rows.push(`<tr><td><b>${E(j.job_no)}</b><br><span class="muted">${E(j.status)}</span></td><td>${E(tech?.full_name||'Unassigned')}</td><td>USD ${(Number(p?.revenue_usd||0)-Number(p?.cost_usd||0)).toFixed(2)}<br>LRD ${(Number(p?.revenue_lrd||0)-Number(p?.cost_lrd||0)).toFixed(2)}</td><td><div class="actions"><button class="btn small" onclick="mtechAssignJob('${j.id}')">Assign</button><button class="btn alt small" onclick="mtechJobCost('${j.id}')">Add Cost</button><button class="btn alt small" onclick="mtechTimeline('${j.id}')">Timeline</button></div></td></tr>`)}by('opsJobs').innerHTML=table(['Job','Technician','Net Profit','Actions'],rows)}
 window.mtechRefreshOps=renderOps;
 window.mtechAssignJob=async id=>{const {data}=await SB.from('profiles').select('id,full_name,role').eq('active',true);const opts=(data||[]).filter(x=>['technician','staff','manager','admin','ceo'].includes(x.role)).map(x=>`${x.full_name}::${x.id}`).join('|');modal('Assign Job',formHtml('assignForm',[['user','Technician / Staff','select',opts]]),`<button class="btn" onclick="mtechSaveAssign('${id}')">Assign Job</button>`)};
 window.mtechSaveAssign=async id=>{const v=formData('assignForm').user.split('::'),uid=v[1]||null;const {error}=await SB.from('jobs').update({assigned_user_id:uid}).eq('id',id);if(error)return alert(error.message);await SB.from('job_timeline').insert({job_id:id,event_type:'assignment',title:'Job assigned',details:v[0]||''});closeModal();await loadAll(true);renderOps()};
 window.mtechJobCost=id=>modal('Add Job Cost',formHtml('costForm',[['cost_type','Cost Type','select','Parts|Transport|Labor|Internet/Data|Other'],['description','Description','text',''],['currency','Currency','select','USD|LRD'],['amount','Amount','number','0']]),`<button class="btn" onclick="mtechSaveCost('${id}')">Save Cost</button>`);
 window.mtechSaveCost=async id=>{const f=formData('costForm');f.job_id=id;f.amount=Number(f.amount||0);const {error}=await SB.from('job_costs').insert(f);if(error)return alert(error.message);await SB.from('job_timeline').insert({job_id:id,event_type:'cost',title:'Job cost recorded',details:`${f.currency} ${f.amount} · ${f.description||f.cost_type}`});closeModal();renderOps()};
 window.mtechTimeline=async id=>{const {data}=await SB.from('job_timeline').select('*').eq('job_id',id).order('created_at',{ascending:false});modal('Job Activity Timeline',(data||[]).map(x=>`<div class="notice"><b>${E(x.title)}</b><br>${E(x.details||'')}<br><span class="muted">${dt(x.created_at)}</span></div>`).join('')||'<p class="muted">No timeline events yet.</p>')};
 // Duplicate protection for customer records.
 try{const oldSaveSimple=saveSimple;saveSimple=async function(t,f){if(t==='customers'){const obj=formData(f);const {data}=await SB.rpc('find_customer_duplicates',{p_phone:obj.phone||'',p_email:obj.email||null,p_name:obj.full_name||null});if((data||[]).length){const names=data.map(x=>`${x.full_name} (${x.phone||''})`).join('\n');if(!confirm('Possible duplicate customer found:\n'+names+'\n\nSave another customer anyway?'))return}}if(!navigator.onLine&&['customers','organizations','expenses','appointments','reminders'].includes(t)){queueMutation(t,formData(f));closeModal();alert('Internet is offline. This record is saved safely on this device and will sync when connection returns.');return}return oldSaveSimple(t,f)}}catch(e){console.warn(e)}
 function queueMutation(table,obj){const q=JSON.parse(localStorage.getItem('mtech-offline-queue')||'[]');q.push({table,obj,at:new Date().toISOString()});localStorage.setItem('mtech-offline-queue',JSON.stringify(q))}
 async function flushQueue(){if(!navigator.onLine)return;let q=JSON.parse(localStorage.getItem('mtech-offline-queue')||'[]');if(!q.length)return;const keep=[];for(const x of q){const {error}=await SB.from(x.table).insert(x.obj);if(error)keep.push(x)}localStorage.setItem('mtech-offline-queue',JSON.stringify(keep));if(q.length&&!keep.length)alert('M-TECH synced your offline saved records successfully.')}
 window.addEventListener('online',flushQueue);setTimeout(flushQueue,3500);
 // Smart automatic follow-ups.
 async function refreshTasks(){try{if(session)await SB.rpc('refresh_smart_tasks')}catch{}}setTimeout(refreshTasks,5000);setInterval(refreshTasks,15*60*1000);
 // Emergency lock + owner control.
 async function checkLock(){if(!session||!profile)return;const {data}=await SB.from('system_control').select('*').eq('id',1).maybeSingle();if(!data)return;if(data.emergency_lock&&!['ceo','admin'].includes(profile.role)){document.body.innerHTML=`<main style="min-height:100vh;display:grid;place-items:center;background:#070911;color:white;font-family:system-ui;padding:24px"><div style="max-width:520px;text-align:center"><img src="../mtech-logo.png" style="width:120px"><h1>M-TECH Temporarily Locked</h1><p>${E(data.lock_message||'The CEO has temporarily paused system changes. Please contact management.')}</p><button onclick="location.reload()" style="padding:12px 18px;border:0;border-radius:12px">Try Again</button></div></main>`}if(['ceo','admin'].includes(profile.role)){const h=by('expertHealth');if(h&&!by('lockControls'))h.insertAdjacentHTML('beforeend',`<div id="lockControls" class="card" style="margin-top:14px"><h3>CEO Emergency Lock</h3><p class="muted">Temporarily block ordinary users while preserving CEO/Admin access.</p><div class="actions"><button class="btn danger small" onclick="mtechSetLock(true)">Lock System</button><button class="btn alt small" onclick="mtechSetLock(false)">Unlock System</button></div></div>`)}}
 window.mtechSetLock=async locked=>{const message=locked?(prompt('Message ordinary users will see:','M-TECH is temporarily locked by the CEO for maintenance/reconciliation.')||'M-TECH is temporarily locked by the CEO.') : null;if(!confirm(locked?'Temporarily lock the system for ordinary users?':'Unlock the system for ordinary users?'))return;const {error}=await SB.rpc('set_emergency_lock',{p_locked:locked,p_message:message});if(error)return alert(error.message);alert(locked?'System lock enabled. CEO/Admin access remains available.':'System unlocked.');checkLock()};
 // Technician-only simplification: their assigned jobs are the primary view.
 function technicianMode(){if(!profile||profile.role!=='technician')return;document.querySelectorAll('.navbtn').forEach(b=>{const p=b.dataset.panel;if(p&&!['dashboard','jobs','expertOps','expertTasks','expertInventory'].includes(p))b.style.display='none'});const mine=(state.jobs||[]).filter(j=>j.assigned_user_id===profile.id);const m=by('metrics');if(m)m.insertAdjacentHTML('afterbegin',`<div class="card metric"><span class="muted">My Assigned Jobs</span><b>${mine.length}</b></div>`)}
 // Add before/after photo and job checklist affordance to job editor through separate quick tool.
 const oldRenderJobs=renderJobs;renderJobs=function(){oldRenderJobs();document.querySelectorAll('#jobsTable tbody tr').forEach((tr,i)=>{const j=(state.jobs||[])[i];if(!j)return;const cell=tr.lastElementChild;if(cell&&!cell.querySelector('.expertJob'))cell.insertAdjacentHTML('beforeend',` <button class="btn alt small expertJob" onclick="mtechTimeline('${j.id}')">Activity</button>`)})};
 // Wait until authenticated app is ready.
 const ready=setInterval(()=>{if(profile&&state){clearInterval(ready);addOpsPanels();technicianMode();checkLock();}},500);
})();

// Private Staff & Leadership Profile Photos
(function(){
 const photoCache=new Map();
 const safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 async function signed(path){if(!path)return'';const cached=photoCache.get(path);if(cached&&cached.expires>Date.now())return cached.url;const {data,error}=await SB.storage.from('staff-files').createSignedUrl(path,3600);if(error||!data?.signedUrl)return'';const url=data.signedUrl;photoCache.set(path,{url,expires:Date.now()+50*60*1000});return url}
 function initials(name){return String(name||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'?'}
 async function enhance(){const root=document.getElementById('staffTable');if(!root||!Array.isArray(state?.staff))return;const rows=[...root.querySelectorAll('tbody tr')];for(const tr of rows){const docBtn=tr.querySelector('button[data-action="staff-doc"]');if(!docBtn)continue;const id=docBtn.dataset.id,s=state.staff.find(x=>x.id===id);if(!s)continue;const nameCell=tr.children[1];if(nameCell&&!nameCell.querySelector('.mtech-staff-avatar')){const wrap=document.createElement('span');wrap.className='mtech-staff-avatar';wrap.style.cssText='display:inline-grid;place-items:center;width:48px;height:48px;border-radius:50%;margin-right:10px;vertical-align:middle;overflow:hidden;background:#17213b;border:1px solid #445171;font-weight:900;color:#8fe9e5';wrap.textContent=initials(s.full_name);nameCell.prepend(wrap);const path=s.photo_storage_path||s.photo_path;if(path){const u=await signed(path);if(u){wrap.textContent='';const img=document.createElement('img');img.src=u;img.alt=s.full_name+' profile photo';img.style.cssText='width:100%;height:100%;object-fit:cover';wrap.appendChild(img)}}}
   const actions=tr.lastElementChild;if(actions&&!actions.querySelector('.mtech-photo-btn')){const b=document.createElement('button');b.type='button';b.className='btn alt small mtech-photo-btn';b.textContent=(s.photo_storage_path||s.photo_path)?'Profile Photo':'Add Photo';b.onclick=()=>window.mtechStaffPhoto(id);actions.appendChild(b)}
  }}
 async function compress(file){if(!file||!file.type.startsWith('image/'))throw new Error('Please choose an image file.');if(file.size>20*1024*1024)throw new Error('Photo is too large. Please choose an image under 20 MB.');const img=await new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('Unable to read this photo.'));im.src=URL.createObjectURL(file)});const max=900,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale));const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);return await new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('Unable to prepare photo.')),'image/jpeg',0.82))}
 window.mtechStaffPhoto=async id=>{const s=(state.staff||[]).find(x=>x.id===id);if(!s)return;const path=s.photo_storage_path||s.photo_path;let current='<div style="width:130px;height:130px;border-radius:50%;display:grid;place-items:center;background:#17213b;border:1px solid #445171;font-size:32px;font-weight:900;margin:0 auto 14px">'+safe(initials(s.full_name))+'</div>';if(path){const u=await signed(path);if(u)current='<img src="'+u+'" alt="Profile photo" style="width:130px;height:130px;border-radius:50%;object-fit:cover;display:block;margin:0 auto 14px;border:2px solid #55e5df">'}modal('Staff Profile Photo — '+safe(s.full_name),`<div style="text-align:center">${current}<p class="muted">Private management photo. Visible only to authorized M-TECH management users.</p></div><div class="field"><label>Take or upload profile photo</label><input id="staffPhotoFile" type="file" accept="image/*" capture="user"><div class="hint">Phone: choose Camera or Photo Library. Desktop: choose an image file. Large images are automatically resized for faster loading.</div></div>`,`<div class="actions"><button class="btn" onclick="mtechSaveStaffPhoto('${id}')">${path?'Replace Photo':'Upload Photo'}</button>${path?`<button class="btn danger" onclick="mtechRemoveStaffPhoto('${id}')">Remove Photo</button>`:''}</div>`)};
 window.mtechSaveStaffPhoto=async id=>{const input=document.getElementById('staffPhotoFile'),file=input?.files?.[0];if(!file)return alert('Choose or take a photo first.');try{const blob=await compress(file),path=`profiles/${id}/profile.jpg`;const {error:upErr}=await SB.storage.from('staff-files').upload(path,blob,{contentType:'image/jpeg',upsert:true,cacheControl:'300'});if(upErr)throw upErr;const {error}=await SB.from('staff').update({photo_storage_path:path,photo_path:path}).eq('id',id);if(error)throw error;photoCache.delete(path);const s=(state.staff||[]).find(x=>x.id===id);if(s){s.photo_storage_path=path;s.photo_path=path}closeModal();renderStaff();setTimeout(enhance,100);alert('Profile photo saved successfully.')}catch(e){alert(e.message||'Unable to save profile photo.')}};
 window.mtechRemoveStaffPhoto=async id=>{if(!confirm('Remove this staff profile photo?'))return;const s=(state.staff||[]).find(x=>x.id===id),path=s?.photo_storage_path||s?.photo_path;try{if(path)await SB.storage.from('staff-files').remove([path]);const {error}=await SB.from('staff').update({photo_storage_path:null,photo_path:null}).eq('id',id);if(error)throw error;if(s){s.photo_storage_path=null;s.photo_path=null}photoCache.delete(path);closeModal();renderStaff();setTimeout(enhance,100)}catch(e){alert(e.message||'Unable to remove profile photo.')}};
 const mo=new MutationObserver(()=>setTimeout(enhance,0));mo.observe(document.body,{subtree:true,childList:true});setInterval(enhance,2500);
})();