// M-TECH Expert Operations Upgrade v1.1
(function(){
 const E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const by=id=>document.getElementById(id);
 function ensurePanels(){const nav=by('nav'),content=document.querySelector('.content');if(!nav||!content||by('expertTasks'))return;
  const specs=[['expertTasks','Task Center'],['expertInventory','Inventory & Equipment'],['expertHealth','System Health'],['expertNews','What’s New']];
  specs.forEach(([id,label])=>{const b=document.createElement('button');b.className='navbtn';b.dataset.panel=id;b.textContent=label;b.onclick=()=>{openPanel(id,label);refreshExpert(id)};nav.appendChild(b)});
  content.insertAdjacentHTML('beforeend',`<section id="expertTasks" class="panel"><div class="section-title"><h2>Smart Task Center</h2><button class="btn small" onclick="mtechNewTask()">New Task</button></div><div class="cards" id="taskMetrics"></div><div id="taskTable" class="table-wrap"></div></section>
  <section id="expertInventory" class="panel"><div class="section-title"><h2>Inventory & Customer Equipment</h2><div class="actions"><button class="btn small" onclick="mtechNewInventory()">Add Inventory Item</button><button class="btn alt small" onclick="mtechNewEquipment()">Receive Customer Equipment</button></div></div><div class="grid2"><div><h3>Inventory</h3><div id="inventoryTable" class="table-wrap"></div></div><div><h3>Customer Equipment</h3><div id="equipmentTable" class="table-wrap"></div></div></section>
  <section id="expertHealth" class="panel"><div class="section-title"><h2>System Health & Security</h2><button class="btn alt small" onclick="mtechHealth()">Run Health Check</button></div><div id="healthCards" class="cards"></div><div class="grid2" style="margin-top:14px"><div class="card"><h3>Connectivity</h3><p id="netState"></p><p class="muted">The app autosaves form drafts locally and updates when online.</p></div><div class="card"><h3>Security</h3><p>Session timeout, role access, audit trail, protected Fresh Start and private staff files are enabled.</p><button class="btn alt small" onclick="location.href='management.html#users'">Open User Access Control</button></div></div></section>
  <section id="expertNews" class="panel"><div class="section-title"><h2>What’s New</h2><span class="muted">M-TECH release history</span></div><div id="releaseList"></div></section>`);
 }
 function addCommandBar(){if(by('expertCommand'))return;const top=document.querySelector('.topbar');if(!top)return;const box=document.createElement('div');box.id='expertCommand';box.className='expert-command';box.innerHTML=`<button class="btn alt small" id="globalBack">‹ Back</button><input id="globalSearch" placeholder="Search customer, request, invoice, job, staff…"><span id="syncBadge" class="pill">Online</span><button class="btn alt small" id="helpBtn">? Help</button>`;top.insertAdjacentElement('afterend',box);by('globalBack').onclick=()=>history.length>1?history.back():openPanel('dashboard','Dashboard');by('globalSearch').oninput=e=>searchAll(e.target.value);by('helpBtn').onclick=help;
 }
 function searchAll(term){term=term.trim().toLowerCase();let root=by('globalSearchResults');if(!root){root=document.createElement('div');root.id='globalSearchResults';root.className='search-results';document.body.appendChild(root)}if(term.length<2){root.innerHTML='';root.classList.remove('show');return}const sets=[['Customer',state.customers||[],'full_name'],['Request',state.requests||[],'request_no'],['Job',state.jobs||[],'job_no'],['Quotation',state.quotes||[],'quotation_no'],['Invoice',state.invoices||[],'invoice_no'],['Staff',state.staff||[],'full_name']];let out=[];sets.forEach(([label,rows,key])=>rows.forEach(r=>{if(JSON.stringify(r).toLowerCase().includes(term))out.push({label,key:r[key]||label,row:r})}));root.innerHTML=out.slice(0,20).map(x=>`<button onclick="mtechSearchOpen('${x.label}','${x.row.id}')"><b>${E(x.label)}</b> ${E(x.key)}</button>`).join('')||'<div class="notice">No matching record.</div>';root.classList.add('show')}
 window.mtechSearchOpen=(type,id)=>{by('globalSearchResults')?.classList.remove('show');by('globalSearch').value='';const map={Request:['requests','Customer Requests'],Job:['jobs','Jobs / Work Orders'],Quotation:['quotes','Quotations'],Invoice:['invoices','Invoices & Payments'],Customer:['customers','Customers & Organizations'],Staff:['staff','Staff & Leadership']};const m=map[type];if(m)openPanel(m[0],m[1]);if(type==='Request')action('view-request',id);if(type==='Job')action('edit-job',id)};
 function autosave(){document.addEventListener('input',e=>{const el=e.target;if(!el.name&&!el.id)return;if(!el.closest('.modal')&&!el.closest('form'))return;try{localStorage.setItem('mtech-draft:'+location.pathname+':'+(el.name||el.id),el.value)}catch{}});document.addEventListener('focusin',e=>{const el=e.target;if(!el.name&&!el.id)return;if(el.value)return;try{const v=localStorage.getItem('mtech-draft:'+location.pathname+':'+(el.name||el.id));if(v!==null)el.value=v}catch{}})}
 function net(){const b=by('syncBadge');if(b)b.textContent=navigator.onLine?'Online · Synced':'Offline · Drafts Safe';const n=by('netState');if(n)n.innerHTML=navigator.onLine?'<span class="success">● Online</span>':'<span class="error">● Offline</span>';}
 async function tasks(){const {data}=await SB.from('task_center').select('*').order('due_at',{ascending:true}).limit(200);const rows=data||[],open=rows.filter(x=>x.status==='open'),over=open.filter(x=>x.due_at&&new Date(x.due_at)<new Date());by('taskMetrics').innerHTML=[['Open',open.length],['Overdue',over.length],['High Priority',open.filter(x=>x.priority==='high'||x.priority==='urgent').length],['Automatic',open.filter(x=>x.auto_generated).length]].map(x=>`<div class="card metric"><span class="muted">${x[0]}</span><b>${x[1]}</b></div>`).join('');by('taskTable').innerHTML=table(['Task','Type','Priority','Due','Status','Action'],rows.map(x=>`<tr><td><b>${E(x.title)}</b><br><span class="muted">${E(x.details||'')}</span></td><td>${E(x.task_type)}</td><td>${E(x.priority)}</td><td>${x.due_at?dt(x.due_at):'—'}</td><td><span class="pill">${E(x.status)}</span></td><td>${x.status==='open'?`<button class="btn small" onclick="mtechDoneTask('${x.id}')">Done</button>`:''}</td></tr>`))}
 window.mtechNewTask=()=>modal('New Task',formHtml('expertTaskForm',[['title','Task','text',''],['details','Details','textarea',''],['priority','Priority','select','normal|high|urgent'],['due_at','Due','datetime-local','']]),`<button class="btn" onclick="mtechSaveTask()">Save Task</button>`);
 window.mtechSaveTask=async()=>{const f=formData('expertTaskForm');f.status='open';f.task_type='manual';f.due_at=f.due_at?new Date(f.due_at).toISOString():null;const {error}=await SB.from('task_center').insert(f);if(error)return alert(error.message);closeModal();tasks()};
 window.mtechDoneTask=async id=>{await SB.from('task_center').update({status:'completed',completed_at:new Date().toISOString()}).eq('id',id);tasks()};
 async function inventory(){const [i,e]=await Promise.all([SB.from('inventory_items').select('*').order('name'),SB.from('customer_equipment').select('*,customers(full_name),jobs(job_no)').order('received_at',{ascending:false})]);by('inventoryTable').innerHTML=table(['Item','Qty','Reorder','Cost','Status'],(i.data||[]).map(x=>`<tr><td><b>${E(x.name)}</b><br><span class="muted">${E(x.sku||'')}</span></td><td>${x.quantity} ${E(x.unit)}</td><td>${x.reorder_level}</td><td>${money(x.unit_cost,x.currency)}</td><td>${Number(x.quantity)<=Number(x.reorder_level)?'<span class="error">Low</span>':'OK'}</td></tr>`));by('equipmentTable').innerHTML=table(['Customer','Equipment','Serial','Status','Received'],(e.data||[]).map(x=>`<tr><td>${E(x.customers?.full_name||'')}</td><td>${E([x.brand,x.model,x.equipment_type].filter(Boolean).join(' '))}</td><td>${E(x.serial_no||'')}</td><td><span class="pill">${E(x.status)}</span></td><td>${dt(x.received_at)}</td></tr>`))}
 window.mtechNewInventory=()=>modal('Add Inventory Item',formHtml('invForm',[['name','Item Name','text',''],['sku','SKU','text',''],['category','Category','text',''],['quantity','Quantity','number','0'],['reorder_level','Reorder Level','number','0'],['unit','Unit','text','pcs'],['currency','Currency','select','USD|LRD'],['unit_cost','Unit Cost','number','0']]),`<button class="btn" onclick="mtechSaveInventory()">Save Item</button>`);
 window.mtechSaveInventory=async()=>{const f=formData('invForm');['quantity','reorder_level','unit_cost'].forEach(k=>f[k]=Number(f[k]||0));const {error}=await SB.from('inventory_items').insert(f);if(error)return alert(error.message);closeModal();inventory()};
 window.mtechNewEquipment=()=>{const opts=(state.customers||[]).map(c=>c.full_name+'::'+c.id).join('|');modal('Receive Customer Equipment',formHtml('eqForm',[['customer','Customer','select',opts],['equipment_type','Equipment Type','text',''],['brand','Brand','text',''],['model','Model','text',''],['serial_no','Serial Number','text',''],['accessories_received','Accessories Received','textarea',''],['condition_received','Condition Received','textarea','']]),`<button class="btn" onclick="mtechSaveEquipment()">Receive Equipment</button>`)};
 window.mtechSaveEquipment=async()=>{const f=formData('eqForm'),p=f.customer.split('::');delete f.customer;f.customer_id=p[1]||null;const {error}=await SB.from('customer_equipment').insert(f);if(error)return alert(error.message);closeModal();inventory()};
 async function health(){const {data,error}=await SB.rpc('mtech_system_health');if(error)return alert(error.message);const h=data||{};by('healthCards').innerHTML=[['Database',h.database],['Open Jobs',h.open_jobs],['Unpaid Invoices',h.unpaid_invoices],['Pending Tasks',h.pending_tasks],['Low Inventory',h.inventory_low],['Last Backup',h.last_backup?new Date(h.last_backup).toLocaleString():'Not recorded']].map(x=>`<div class="card metric"><span class="muted">${E(x[0])}</span><b>${E(x[1]??'')}</b></div>`).join('');net()}
 window.mtechHealth=health;
 async function news(){const {data}=await SB.from('release_notes').select('*').order('published_at',{ascending:false});by('releaseList').innerHTML=(data||[]).map(x=>`<div class="card" style="margin-bottom:12px"><div class="pill">Version ${E(x.version)}</div><h3>${E(x.title)}</h3><p>${E(x.notes)}</p><span class="muted">${dt(x.published_at)}</span></div>`).join('')||'<p class="muted">No release notes yet.</p>'}
 function help(){const p=document.querySelector('.panel.active')?.id||'dashboard';const tips={dashboard:'Use this as your CEO command center. Review new requests, jobs, money due and appointments.',requests:'Open a request to review customer details and evidence, then quote it or convert it to a job.',jobs:'Manage diagnosis, assignment, work performed, completion and invoicing.',expertTasks:'Use Today/Overdue tasks so no customer or payment follow-up is forgotten.',expertInventory:'Track M-TECH stock and customer devices received for service.',expertHealth:'Check connectivity, database condition, backups and key risk indicators.',settings:'CEO controls company details, defaults, services and protected Fresh Start.'};modal('Help · '+p,`<p>${E(tips[p]||'This page is part of your M-TECH business workflow. Use the available actions to manage records safely.')}</p>`)}
 function badges(){const unread=(state.notifications||[]).filter(n=>!n.read_at).length;document.querySelectorAll('.navbtn').forEach(b=>{if(b.dataset.panel==='notifications'){let s=b.querySelector('.navbadge');if(!s){s=document.createElement('span');s.className='navbadge';b.appendChild(s)}s.textContent=unread||'';s.style.display=unread?'inline-flex':'none'}})}
 async function refreshExpert(id){if(id==='expertTasks')await tasks();if(id==='expertInventory')await inventory();if(id==='expertHealth')await health();if(id==='expertNews')await news()}
 const oldRender=renderAll;renderAll=function(){oldRender();badges()};
 ensurePanels();addCommandBar();autosave();net();window.addEventListener('online',net);window.addEventListener('offline',net);document.addEventListener('visibilitychange',()=>{if(!document.hidden)net()});
})();