(function(){
function e(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function bootHub(){
 if(typeof SB==='undefined'||!document.getElementById('nav')||!document.querySelector('.content')){setTimeout(bootHub,250);return;}
 if(document.querySelector('[data-panel="hub"]'))return;
 initHub();
}
function initHub(){
 const nav=document.getElementById('nav');
 const b=document.createElement('button'); b.className='navbtn'; b.dataset.panel='hub'; b.textContent='Problem Solving & Innovation Hub';
 const qr=Array.from(nav.children).find(x=>x.textContent.includes('QR Distribution'));
 if(qr)nav.insertBefore(b,qr);else nav.appendChild(b);
 const content=document.querySelector('.content'); const sec=document.createElement('section'); sec.id='hub'; sec.className='panel';
 sec.innerHTML=`<div class="section-title"><div><h2>M-TECH Problem Solving, Innovation & Community Hub</h2><span class="muted">Bring a problem. Collaborate. Innovate. Build a solution.</span></div><div class="actions"><button class="btn small" id="hubNewProblem">Solve a Problem</button><button class="btn alt small" id="hubNewIdea">New Innovation</button><button class="btn alt small" id="hubNewAccount">Manage Accounts</button></div></div>
 <div class="cards" id="hubMetrics"></div>
 <div class="grid2" style="margin-top:14px"><div class="card"><h3>Problem Solving Workspaces</h3><div id="hubProblems"></div></div><div class="card"><h3>Innovation Lab</h3><div id="hubInnovations"></div></div></div>
 <div class="grid2" style="margin-top:14px"><div class="card"><h3>M-TECH Community</h3><div id="hubCommunity"></div><button class="btn alt small" id="hubNewPost">New Community Post</button></div><div class="card"><h3>Knowledge Bank</h3><div id="hubKnowledge"></div><button class="btn alt small" id="hubNewKnowledge">Add Knowledge</button></div></div>
 <div class="grid2" style="margin-top:14px"><div class="card"><h3>Skills & Learning Center</h3><div id="hubLearning"></div></div><div class="card"><h3>Opportunity Board</h3><div id="hubOpportunities"></div><button class="btn alt small" id="hubNewOpportunity">Add Opportunity</button></div></div>
 <div class="card" style="margin-top:14px"><div class="section-title"><h3>Hub Account Administration</h3><button class="btn small" id="hubAddAccount">Add / Invite Account</button></div><p class="muted">CEO control for students, contributors, mentors, moderators, instructors, partners and collaborators. Business-management permissions remain separate.</p><div id="hubAccounts"></div></div>`; content.appendChild(sec);
 b.onclick=()=>{document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id==='hub'));document.querySelectorAll('.navbtn').forEach(x=>x.classList.toggle('active',x===b));document.getElementById('pageTitle').textContent='Problem Solving & Innovation Hub';loadHub();};
 document.getElementById('hubNewProblem').onclick=()=>workspaceForm('problem'); document.getElementById('hubNewIdea').onclick=()=>workspaceForm('innovation'); document.getElementById('hubNewAccount').onclick=()=>accountManager(); document.getElementById('hubAddAccount').onclick=()=>accountForm(); document.getElementById('hubNewPost').onclick=communityForm; document.getElementById('hubNewKnowledge').onclick=knowledgeForm; document.getElementById('hubNewOpportunity').onclick=opportunityForm;
 loadHub();
}
async function loadHub(){
 const [a,w,k,p,o,l]=await Promise.all([SB.from('hub_accounts').select('*').order('created_at',{ascending:false}),SB.from('hub_workspaces').select('*').order('created_at',{ascending:false}),SB.from('hub_knowledge').select('*').order('created_at',{ascending:false}).limit(20),SB.from('hub_community_posts').select('*').order('created_at',{ascending:false}).limit(20),SB.from('hub_opportunities').select('*').order('created_at',{ascending:false}).limit(20),SB.from('hub_learning_paths').select('*').order('sort_order',{ascending:true})]);
 const accounts=a.data||[],work=w.data||[],knowledge=k.data||[],posts=p.data||[],opps=o.data||[],paths=l.data||[];
 const probs=work.filter(x=>x.workspace_type==='problem'),innov=work.filter(x=>x.workspace_type==='innovation');
 document.getElementById('hubMetrics').innerHTML=[['Active Hub Accounts',accounts.filter(x=>x.status==='active').length],['Open Problems',probs.filter(x=>x.status!=='closed').length],['Innovation Projects',innov.length],['Knowledge Articles',knowledge.length],['Community Posts',posts.length],['Opportunities',opps.filter(x=>x.status==='active').length]].map(x=>`<div class="card metric"><span class="muted">${x[0]}</span><b>${x[1]}</b></div>`).join('');
 const list=(arr,empty)=>arr.length?arr.map(x=>`<div class="notice"><b>${e(x.title||x.full_name)}</b><br><span class="muted">${e(x.category||x.account_type||x.organization||'')}</span> ${x.status?`<span class="pill">${e(x.status)}</span>`:''}</div>`).join(''):`<p class="muted">${empty}</p>`;
 document.getElementById('hubProblems').innerHTML=list(probs,'No problem workspaces yet.'); document.getElementById('hubInnovations').innerHTML=list(innov,'No innovations yet.'); document.getElementById('hubCommunity').innerHTML=list(posts,'No community posts yet.'); document.getElementById('hubKnowledge').innerHTML=list(knowledge,'No knowledge entries yet.'); document.getElementById('hubLearning').innerHTML=list(paths,'Learning paths will appear here.'); document.getElementById('hubOpportunities').innerHTML=list(opps,'No active opportunities yet.');
 document.getElementById('hubAccounts').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Name</th><th>Type</th><th>Institution</th><th>Status</th><th>Contact</th><th>Action</th></tr></thead><tbody>${accounts.length?accounts.map(x=>`<tr><td><b>${e(x.full_name)}</b></td><td>${e(x.account_type)}</td><td>${e(x.institution||'')}</td><td><span class="pill">${e(x.status)}</span></td><td>${e(x.phone||x.email||'')}</td><td><button class="btn alt small" onclick="window.hubToggle('${x.id}','${x.status==='active'?'suspended':'active'}')">${x.status==='active'?'Suspend':'Activate'}</button></td></tr>`).join(''):'<tr><td colspan="6" class="muted">No Hub accounts yet.</td></tr>'}</tbody></table></div>`;
}
function show(title,body){window.modal?modal(title,body):alert(title)}
function workspaceForm(type){show(type==='innovation'?'New Innovation Lab Project':'Solve a Problem',`<div class="field"><label>Title</label><input id="hwTitle"></div><div class="field"><label>Category</label><input id="hwCat" placeholder="Technology, Business, Research, Education..."></div><div class="field"><label>${type==='innovation'?'Idea / opportunity':'Problem statement'}</label><textarea id="hwProblem"></textarea></div><div class="field"><label>Target users / beneficiaries</label><input id="hwTarget"></div><div class="field"><label>Visibility</label><select id="hwVis"><option value="private">Private</option><option value="community">Community</option></select></div><button class="btn" onclick="hubSaveWorkspace('${type}')">Save Workspace</button>`)}
window.hubSaveWorkspace=async type=>{const {data:me}=await SB.from('hub_accounts').select('id').eq('auth_user_id',session.user.id).maybeSingle();const {error}=await SB.from('hub_workspaces').insert({owner_account_id:me?.id||null,workspace_type:type,title:document.getElementById('hwTitle').value.trim(),category:document.getElementById('hwCat').value.trim(),problem_statement:document.getElementById('hwProblem').value.trim(),target_users:document.getElementById('hwTarget').value.trim(),visibility:document.getElementById('hwVis').value});if(error)return alert(error.message);closeModal();loadHub()};
function accountManager(){document.getElementById('hubAccounts')?.scrollIntoView({behavior:'smooth'})}
function accountForm(){show('Add / Invite Hub Account',`<div class="grid2"><div class="field"><label>Full name</label><input id="haName"></div><div class="field"><label>Account type</label><select id="haType"><option>student</option><option>contributor</option><option>mentor</option><option>moderator</option><option>instructor</option><option>partner</option></select></div></div><div class="grid2"><div class="field"><label>Email</label><input id="haEmail" type="email"></div><div class="field"><label>Phone</label><input id="haPhone"></div></div><div class="grid2"><div class="field"><label>Institution</label><input id="haInstitution"></div><div class="field"><label>Program / field</label><input id="haProgram"></div></div><button class="btn" onclick="hubSaveAccount()">Create Hub Record</button><p class="muted">Authentication/login invitation can be added separately; this creates the managed Hub identity first.</p>`)}
window.hubSaveAccount=async()=>{const row={full_name:document.getElementById('haName').value.trim(),account_type:document.getElementById('haType').value,email:document.getElementById('haEmail').value.trim()||null,phone:document.getElementById('haPhone').value.trim()||null,institution:document.getElementById('haInstitution').value.trim()||null,program:document.getElementById('haProgram').value.trim()||null,status:'active',created_by:session.user.id};const {error}=await SB.from('hub_accounts').insert(row);if(error)return alert(error.message);closeModal();loadHub()};
window.hubToggle=async(id,status)=>{const {error}=await SB.from('hub_accounts').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error)return alert(error.message);loadHub()};
function communityForm(){show('New M-TECH Community Post',`<div class="field"><label>Title</label><input id="hcTitle"></div><div class="field"><label>Type</label><select id="hcType"><option>question</option><option>discussion</option><option>solution</option><option>project</option></select></div><div class="field"><label>Post</label><textarea id="hcBody"></textarea></div><button class="btn" onclick="hubSavePost()">Publish</button>`)}
window.hubSavePost=async()=>{const {data:me}=await SB.from('hub_accounts').select('id').eq('auth_user_id',session.user.id).maybeSingle();const {error}=await SB.from('hub_community_posts').insert({author_account_id:me?.id||null,post_type:document.getElementById('hcType').value,title:document.getElementById('hcTitle').value.trim(),body:document.getElementById('hcBody').value.trim(),status:'published'});if(error)return alert(error.message);closeModal();loadHub()};
function knowledgeForm(){show('Add to Knowledge Bank',`<div class="field"><label>Title</label><input id="hkTitle"></div><div class="field"><label>Category</label><input id="hkCat"></div><div class="field"><label>Problem</label><textarea id="hkProblem"></textarea></div><div class="field"><label>Cause / finding</label><textarea id="hkCause"></textarea></div><div class="field"><label>Verified solution</label><textarea id="hkSolution"></textarea></div><button class="btn" onclick="hubSaveKnowledge()">Save Knowledge</button>`)}
window.hubSaveKnowledge=async()=>{const {data:me}=await SB.from('hub_accounts').select('id').eq('auth_user_id',session.user.id).maybeSingle();const {error}=await SB.from('hub_knowledge').insert({title:document.getElementById('hkTitle').value.trim(),category:document.getElementById('hkCat').value.trim(),problem:document.getElementById('hkProblem').value.trim(),cause:document.getElementById('hkCause').value.trim(),solution:document.getElementById('hkSolution').value.trim(),created_by:me?.id||null,visibility:'community',verified:true});if(error)return alert(error.message);closeModal();loadHub()};
function opportunityForm(){show('Add Opportunity',`<div class="grid2"><div class="field"><label>Type</label><select id="hoType"><option>internship</option><option>scholarship</option><option>training</option><option>job</option><option>competition</option><option>project</option></select></div><div class="field"><label>Deadline</label><input id="hoDeadline" type="date"></div></div><div class="field"><label>Title</label><input id="hoTitle"></div><div class="field"><label>Organization</label><input id="hoOrg"></div><div class="field"><label>Description</label><textarea id="hoDesc"></textarea></div><div class="field"><label>Application link</label><input id="hoUrl"></div><button class="btn" onclick="hubSaveOpportunity()">Publish Opportunity</button>`)}
window.hubSaveOpportunity=async()=>{const {error}=await SB.from('hub_opportunities').insert({opportunity_type:document.getElementById('hoType').value,title:document.getElementById('hoTitle').value.trim(),organization:document.getElementById('hoOrg').value.trim(),description:document.getElementById('hoDesc').value.trim(),application_url:document.getElementById('hoUrl').value.trim(),deadline:document.getElementById('hoDeadline').value||null,status:'active'});if(error)return alert(error.message);closeModal();loadHub()};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootHub);else bootHub();
})();