const SB=supabase.createClient('https://vsirepejlaytbqhhikev.supabase.co','sb_publishable_vQULGJJZNtuT_MZCSqomiQ_URYS4BQp',{auth:{persistSession:true,autoRefreshToken:true}});let session=null,profile=null,state={};const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));const money=(v,c)=>`${c||''} ${Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2})}`;const dt=v=>v?new Date(v).toLocaleString():'';const date=v=>v?new Date(v).toLocaleDateString():'';const short=s=>esc(String(s||'').slice(0,90));
function msg(t,e=false){$('loginMsg').className=e?'error':'muted';$('loginMsg').textContent=t}
async function init(){const {data}=await SB.auth.getSession();session=data.session;if(session)await enterApp();SB.auth.onAuthStateChange(async(_e,s)=>{session=s;if(s)await enterApp();else showLogin()});bind()}
function bind(){$('loginBtn').onclick=login;$('setupBtn').onclick=setup;$('logoutBtn').onclick=()=>SB.auth.signOut();$('refreshBtn').onclick=()=>loadAll(true);document.querySelectorAll('.navbtn').forEach(b=>b.onclick=()=>openPanel(b.dataset.panel,b.textContent));document.body.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;await action(b.dataset.action,b.dataset.id)});$('requestSearch').oninput=renderRequests;$('requestStatus').onchange=renderRequests}
function showLogin(){$('loginView').classList.remove('hidden');$('appView').classList.add('hidden')}
async function login(){msg('Signing in…');const {error}=await SB.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});if(error)msg(error.message,true)}
async function setup(){const email=$('loginEmail').value.trim(),password=$('loginPassword').value;if(email.toLowerCase()!=='johnsonmulbahe@gmail.com'){msg('For the first CEO account, use the CEO email johnsonmulbahe@gmail.com.',true);return}if(password.length<8){msg('Choose a password with at least 8 characters.',true);return}msg('Creating CEO account…');const {data,error}=await SB.auth.signUp({email,password,options:{data:{full_name:'Mulbah E. Johnson'}}});if(error){msg(error.message,true);return}msg(data.session?'CEO account created and signed in.':'CEO account created. If email confirmation is enabled, confirm the email and then sign in.')}
async function enterApp(){const u=session.user;let {data:p,error}=await SB.from('profiles').select('*').eq('id',u.id).maybeSingle();if(error){console.error(error);return}profile=p;if(!p||!p.active){await SB.auth.signOut();msg('This account is not authorized for M-TECH management.',true);return}$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('userLine').textContent=`${p.full_name||u.email} · ${p.role.toUpperCase()}`;await SB.from('profiles').update({last_login_at:new Date().toISOString()}).eq('id',u.id);await loadAll()}
function openPanel(id,title){document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.navbtn').forEach(x=>x.classList.toggle('active',x.dataset.panel===id));$('pageTitle').textContent=title||id}
async function q(table,select='*',opts={}){let x=SB.from(table).select(select);if(opts.order)x=x.order(opts.order,{ascending:opts.asc??false});if(opts.limit)x=x.limit(opts.limit);const {data,error}=await x;if(error){console.error(table,error);return[]}return data||[]}
async function loadAll(silent=false){if(!silent)$('pageTitle').textContent='Loading…';const snap=await SB.rpc('ceo_dashboard_snapshot');state.metrics=snap.data||{};const [requests,jobs,quotes,invoices,customers,orgs,staff,appointments,reminders,expenses,assets,services,settings,notifications,audit]=await Promise.all([
 q('service_requests','*,customers(full_name,phone,whatsapp,email,area)',{order:'created_at',limit:100}),q('jobs','*',{order:'created_at',limit:100}),q('quotations','*',{order:'created_at',limit:100}),q('invoices','*',{order:'created_at',limit:100}),q('customers','*',{order:'created_at',limit:100}),q('organizations','*',{order:'created_at',limit:100}),q('staff','*',{order:'created_at',limit:100}),q('appointments','*',{order:'scheduled_at',asc:true,limit:100}),q('reminders','*',{order:'due_at',asc:true,limit:100}),q('expenses','*',{order:'expense_date',limit:100}),q('assets','*',{order:'created_at',limit:100}),q('service_categories','*',{order:'sort_order',asc:true,limit:100}),q('app_settings','*',{order:'updated_at',limit:100}),q('notifications','*',{order:'created_at',limit:100}),q('audit_log','*',{order:'created_at',limit:100})]);Object.assign(state,{requests,jobs,quotes,invoices,customers,orgs,staff,appointments,reminders,expenses,assets,services,settings,notifications,audit});renderAll();if(!silent)$('pageTitle').textContent=document.querySelector('.navbtn.active')?.textContent||'Dashboard'}
function table(headers,rows){return `<table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${headers.length}" class="muted">No records yet.</td></tr>`}</tbody></table>`}
function renderAll(){renderDashboard();renderRequests();renderJobs();renderQuotes();renderInvoices();renderCustomers();renderStaff();renderSchedule();renderFinance();renderSettings();renderNotifications()}
function renderDashboard(){const m=state.metrics||{};$('metrics').innerHTML=[['New Requests',m.new_requests],['Open Jobs',m.open_jobs],['Pending Quotes',m.pending_quotes],['Unpaid Invoices',m.unpaid_invoices],['USD Receivables',money(m.usd_receivables,'USD')],['LRD Receivables',money(m.lrd_receivables,'LRD')],['Active Staff',m.active_staff],['Upcoming Appointments',m.upcoming_appointments]].map(x=>`<div class="card metric"><span class="muted">${x[0]}</span><b>${x[1]??0}</b></div>`).join('');$('recentRequests').innerHTML=(state.requests||[]).slice(0,6).map(r=>`<div class="notice"><b>${esc(r.request_no)}</b><br>${short(r.customers?.full_name)} · ${short(r.problem_summary)}<br><span class="pill">${esc(r.status)}</span></div>`).join('')||'<p class="muted">No requests yet.</p>';$('upcomingAppointments').innerHTML=(state.appointments||[]).filter(a=>new Date(a.scheduled_at)>=new Date()).slice(0,6).map(a=>`<div class="notice"><b>${short(a.title)}</b><br>${dt(a.scheduled_at)} · ${short(a.mode)}</div>`).join('')||'<p class="muted">No upcoming appointments.</p>'}
function renderRequests(){let rows=[...(state.requests||[])];const s=($('requestSearch')?.value||'').toLowerCase(),st=$('requestStatus')?.value||'';if(s)rows=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(s));if(st)rows=rows.filter(r=>r.status===st);$('requestsTable').innerHTML=table(['Request','Customer','Service / Problem','Status','Received','Actions'],rows.map(r=>`<tr><td><b>${esc(r.request_no)}</b></td><td>${esc(r.customers?.full_name)}<br><span class="muted">${esc(r.customers?.phone)}</span></td><td>${esc(r.category_name)}<br><span class="muted">${short(r.problem_summary)}</span></td><td><span class="pill">${esc(r.status)}</span></td><td>${dt(r.created_at)}</td><td><div class="actions"><button class="btn small" data-action="view-request" data-id="${r.id}">Open</button><button class="btn alt small" data-action="quote-request" data-id="${r.id}">Quote</button><button class="btn alt small" data-action="job-request" data-id="${r.id}">Create Job</button></div></td></tr>`))}
function renderJobs(){$('jobsTable').innerHTML=table(['Job','Status','Priority','Scheduled','Completed','Actions'],(state.jobs||[]).map(j=>`<tr><td><b>${esc(j.job_no)}</b></td><td><span class="pill">${esc(j.status)}</span></td><td>${esc(j.priority)}</td><td>${dt(j.scheduled_at)}</td><td>${dt(j.completed_at)}</td><td><div class="actions"><button class="btn small" data-action="edit-job" data-id="${j.id}">Open</button><button class="btn alt small" data-action="invoice-job" data-id="${j.id}">Invoice</button></div></td></tr>`))}
function renderQuotes(){$('quotesTable').innerHTML=table(['Quotation','Currency','Total','Status','Valid Until','Public Link'],(state.quotes||[]).map(x=>`<tr><td><b>${esc(x.quotation_no)}</b></td><td>${esc(x.currency)}</td><td>${money(x.total,x.currency)}</td><td><span class="pill">${esc(x.status)}</span></td><td>${date(x.valid_until)}</td><td><a class="doc-link" target="_blank" href="document.html?type=quote&token=${x.public_token}">Open / Print</a></td></tr>`))}
function renderInvoices(){$('invoicesTable').innerHTML=table(['Invoice','Total','Paid','Balance','Status','Due','Actions'],(state.invoices||[]).map(i=>`<tr><td><b>${esc(i.invoice_no)}</b></td><td>${money(i.total,i.currency)}</td><td>${money(i.paid,i.currency)}</td><td>${money(i.balance,i.currency)}</td><td><span class="pill">${esc(i.status)}</span></td><td>${date(i.due_date)}</td><td><div class="actions"><a class="doc-link" target="_blank" href="document.html?type=invoice&token=${i.public_token}">View</a>${Number(i.balance)>0?`<button class="btn small" data-action="pay-invoice" data-id="${i.id}">Record Payment</button>`:''}</div></td></tr>`))}
function renderCustomers(){$('customersTable').innerHTML=table(['Name','Phone','Email','Area'],(state.customers||[]).map(c=>`<tr><td>${esc(c.full_name)}</td><td>${esc(c.phone)}</td><td>${esc(c.email)}</td><td>${esc(c.area)}</td></tr>`));$('orgsTable').innerHTML=table(['Organization','Type','Phone','Email'],(state.orgs||[]).map(o=>`<tr><td>${esc(o.name)}</td><td>${esc(o.type)}</td><td>${esc(o.phone)}</td><td>${esc(o.email)}</td></tr>`))}
function renderStaff(){$('staffTable').innerHTML=table(['Staff No.','Name','Role','Department','Type','Status','Contact','Actions'],(state.staff||[]).map(s=>`<tr><td>${esc(s.staff_no)}</td><td><b>${esc(s.full_name)}</b></td><td>${esc(s.role_title)}</td><td>${esc(s.team_department)}</td><td>${esc(s.employment_type)}</td><td><span class="pill">${esc(s.status)}</span></td><td>${esc(s.phone)}<br>${esc(s.email)}</td><td><button class="btn small" data-action="staff-doc" data-id="${s.id}">Documents</button></td></tr>`))}
function renderSchedule(){$('appointmentsTable').innerHTML=table(['Title','When','Mode','Status'],(state.appointments||[]).map(a=>`<tr><td>${esc(a.title)}</td><td>${dt(a.scheduled_at)}</td><td>${esc(a.mode)}</td><td><span class="pill">${esc(a.status)}</span></td></tr>`));$('remindersTable').innerHTML=table(['Reminder','Due','Status'],(state.reminders||[]).map(r=>`<tr><td>${esc(r.title)}<br><span class="muted">${short(r.body)}</span></td><td>${dt(r.due_at)}</td><td><span class="pill">${esc(r.status)}</span></td></tr>`))}
function renderFinance(){$('expensesTable').innerHTML=table(['Date','Category','Description','Amount'],(state.expenses||[]).map(e=>`<tr><td>${date(e.expense_date)}</td><td>${esc(e.category)}</td><td>${short(e.description)}</td><td>${money(e.amount,e.currency)}</td></tr>`));$('assetsTable').innerHTML=table(['Asset No.','Name','Category','Status','Cost'],(state.assets||[]).map(a=>`<tr><td>${esc(a.asset_no)}</td><td>${esc(a.name)}</td><td>${esc(a.category)}</td><td><span class="pill">${esc(a.status)}</span></td><td>${money(a.purchase_cost,a.currency)}</td></tr>`))}
function renderSettings(){$('servicesTable').innerHTML=table(['Service','USD','LRD','Warranty','Active','Action'],(state.services||[]).map(s=>`<tr><td><b>${esc(s.name)}</b><br><span class="muted">${short(s.description)}</span></td><td>${s.base_price_usd??''}</td><td>${s.base_price_lrd??''}</td><td>${s.warranty_days??''}</td><td>${s.active?'Yes':'No'}</td><td><button class="btn small" data-action="edit-service" data-id="${s.id}">Edit</button></td></tr>`));$('settingsTable').innerHTML=table(['Key','Value','Updated'],(state.settings||[]).map(s=>`<tr><td>${esc(s.key)}</td><td><code>${esc(JSON.stringify(s.value_json))}</code></td><td>${dt(s.updated_at)}</td></tr>`))}
function renderNotifications(){$('notificationsTable').innerHTML=table(['Title','Message','Priority','Date'],(state.notifications||[]).map(n=>`<tr><td>${esc(n.title)}</td><td>${short(n.body)}</td><td>${esc(n.priority)}</td><td>${dt(n.created_at)}</td></tr>`));$('auditTable').innerHTML=table(['Entity','Action','Date'],(state.audit||[]).map(a=>`<tr><td>${esc(a.entity_type)} ${esc(a.entity_id||'')}</td><td>${esc(a.action)}</td><td>${dt(a.created_at)}</td></tr>`))}
function modal(title,body,buttons=''){ $('modalRoot').innerHTML=`<div class="modal-back"><div class="modal"><div class="section-title"><h2>${title}</h2><button class="btn alt small" onclick="closeModal()">Close</button></div>${body}${buttons}</div></div>`}window.closeModal=()=>{$('modalRoot').innerHTML=''}
async function action(a,id){try{if(a==='view-request')return viewRequest(id);if(a==='quote-request')return quoteRequest(id);if(a==='job-request')return createJob(id);if(a==='edit-job')return editJob(id);if(a==='invoice-job')return invoiceJob(id);if(a==='pay-invoice')return payInvoice(id);if(a==='new-customer')return newCustomer();if(a==='new-org')return newOrg();if(a==='new-staff')return newStaff();if(a==='staff-doc')return staffDocs(id);if(a==='new-appointment')return newAppointment();if(a==='new-reminder')return newReminder();if(a==='new-expense')return newExpense();if(a==='new-asset')return newAsset();if(a==='new-service')return editService();if(a==='edit-service')return editService(id);if(a==='new-setting')return newSetting();if(a==='mark-read'){await SB.from('notifications').update({read_at:new Date().toISOString()}).is('read_at',null);return loadAll(true)}}catch(e){alert(e.message||e)}}
async function viewRequest(id){const r=state.requests.find(x=>x.id===id);const {data:atts}=await SB.from('request_attachments').select('*').eq('request_id',id).order('created_at');let media='';for(const a of atts||[]){const {data:s}=await SB.storage.from('request-media').createSignedUrl(a.storage_path,600);if(!s?.signedUrl)continue;if(a.media_type==='photo')media+=`<div class="media-item"><img src="${s.signedUrl}"><div>${esc(a.file_name)}</div></div>`;else if(a.media_type==='video')media+=`<div class="media-item"><video src="${s.signedUrl}" controls></video><div>${esc(a.file_name)}</div></div>`;else media+=`<div class="media-item"><audio src="${s.signedUrl}" controls style="width:100%"></audio><div>${esc(a.file_name)}</div></div>`}modal(esc(r.request_no),`<div class="grid2"><div class="card"><h3>Customer</h3><b>${esc(r.customers?.full_name)}</b><p>${esc(r.customers?.phone)}<br>${esc(r.customers?.email)}<br>${esc(r.customers?.area)}</p><div class="actions"><a class="btn small" href="tel:${esc(r.customers?.phone)}">Call</a><a class="btn alt small" target="_blank" href="https://wa.me/231${String(r.customers?.phone||'').replace(/\D/g,'').replace(/^0/,'')}">WhatsApp</a></div></div><div class="card"><h3>Request</h3><p><b>${esc(r.category_name)}</b><br>${esc(r.problem_summary)}</p><p>${esc(r.description)}</p><p>Method: ${esc(r.service_method)}<br>Status: <span class="pill">${esc(r.status)}</span></p><select id="reqNewStatus"><option>new</option><option>accepted</option><option>quoted</option><option>in_progress</option><option>completed</option><option>closed</option><option>cancelled</option></select> <button class="btn small" onclick="saveRequestStatus('${r.id}')">Save Status</button></div></div><h3>Attachments</h3><div class="media-grid">${media||'<p class="muted">No saved attachments.</p>'}</div><div class="actions" style="margin-top:15px"><button class="btn" onclick="closeModal();action('quote-request','${r.id}')">Create Quotation</button><button class="btn alt" onclick="closeModal();action('job-request','${r.id}')">Convert to Job</button></div>`)}
window.saveRequestStatus=async id=>{const status=$('reqNewStatus').value;const {error}=await SB.from('service_requests').update({status}).eq('id',id);if(error)alert(error.message);else{closeModal();await loadAll(true)}}
function quoteRequest(id){const r=state.requests.find(x=>x.id===id);modal('Create Quotation',formHtml('quoteForm',[['description','Description','text',r.problem_summary||'Technology Service'],['currency','Currency','select','USD|LRD'],['quantity','Quantity','number','1'],['unit_price','Unit Price','number','0'],['discount','Discount','number','0'],['tax','Tax','number','0'],['valid_until','Valid Until','date',''],['notes','Notes','textarea','']]),`<button class="btn" onclick="saveQuote('${id}')">Create Quotation</button>`)}
window.saveQuote=async id=>{const f=formData('quoteForm');const {data,error}=await SB.rpc('create_quote_from_request',{p_request_id:id,p_currency:f.currency,p_description:f.description,p_quantity:+f.quantity,p_unit_price:+f.unit_price,p_discount:+f.discount,p_tax:+f.tax,p_valid_until:f.valid_until||null,p_notes:f.notes||null});if(error)return alert(error.message);closeModal();await loadAll(true);alert('Quotation '+data.quotation_no+' created.')}
async function createJob(id){const {data,error}=await SB.rpc('create_job_from_request',{p_request_id:id,p_priority:'normal',p_scheduled_at:null});if(error)return alert(error.message);await loadAll(true);alert('Job '+data.job_no+' ready.')}
function editJob(id){const j=state.jobs.find(x=>x.id===id);modal(esc(j.job_no),formHtml('jobForm',[['status','Status','select','open|scheduled|in_progress|waiting_customer|completed|closed|cancelled',j.status],['priority','Priority','select','low|normal|high|urgent',j.priority],['diagnosis','Diagnosis','textarea',j.diagnosis||''],['work_performed','Work Performed','textarea',j.work_performed||''],['scheduled_at','Scheduled At','datetime-local',j.scheduled_at?j.scheduled_at.slice(0,16):''],['warranty_until','Warranty Until','date',j.warranty_until||'']]),`<button class="btn" onclick="saveJob('${id}')">Save Job</button>`)}
window.saveJob=async id=>{const f=formData('jobForm');const patch={status:f.status,priority:f.priority,diagnosis:f.diagnosis||null,work_performed:f.work_performed||null,scheduled_at:f.scheduled_at?new Date(f.scheduled_at).toISOString():null,warranty_until:f.warranty_until||null,completed_at:f.status==='completed'?new Date().toISOString():null};const {error}=await SB.from('jobs').update(patch).eq('id',id);if(error)return alert(error.message);closeModal();await loadAll(true)}
function invoiceJob(id){modal('Create Invoice',formHtml('invoiceForm',[['description','Description','text','Technology Service'],['currency','Currency','select','USD|LRD'],['quantity','Quantity','number','1'],['unit_price','Unit Price','number','0'],['due_date','Due Date','date','']]),`<button class="btn" onclick="saveInvoice('${id}')">Create Invoice</button>`)}
window.saveInvoice=async id=>{const f=formData('invoiceForm');const {data,error}=await SB.rpc('create_invoice_from_job',{p_job_id:id,p_currency:f.currency,p_description:f.description,p_quantity:+f.quantity,p_unit_price:+f.unit_price,p_due_date:f.due_date||null});if(error)return alert(error.message);closeModal();await loadAll(true);alert('Invoice '+data.invoice_no+' created.')}
function payInvoice(id){const i=state.invoices.find(x=>x.id===id);modal('Record Payment',`<p>Invoice <b>${esc(i.invoice_no)}</b> · Balance ${money(i.balance,i.currency)}</p>`+formHtml('payForm',[['amount','Amount','number',i.balance],['method','Payment Method','select','Cash|Mobile Money|Bank Transfer|Card|Other'],['external_reference','Reference','text',''],['notes','Notes','textarea','']]),`<button class="btn" onclick="savePayment('${id}')">Record Payment & Generate Receipt</button>`)}
window.savePayment=async id=>{const f=formData('payForm');const {data,error}=await SB.rpc('record_invoice_payment',{p_invoice_id:id,p_amount:+f.amount,p_method:f.method,p_external_reference:f.external_reference||null,p_notes:f.notes||null});if(error)return alert(error.message);closeModal();await loadAll(true);window.open(`document.html?type=receipt&token=${data.receipt_token}`,'_blank')}
function newCustomer(){modal('Add Customer',formHtml('customerForm',[['full_name','Full Name','text',''],['phone','Phone','text',''],['whatsapp','WhatsApp','text',''],['email','Email','email',''],['area','Area','text','']]),`<button class="btn" onclick="saveSimple('customers','customerForm')">Save Customer</button>`)}
function newOrg(){modal('Add Organization',formHtml('orgForm',[['name','Organization Name','text',''],['type','Type','text',''],['phone','Phone','text',''],['email','Email','email',''],['address_text','Address','textarea','']]),`<button class="btn" onclick="saveSimple('organizations','orgForm')">Save Organization</button>`)}
function newStaff(){modal('Add Staff / Leadership Record',formHtml('staffForm',[['full_name','Full Name','text',''],['role_title','Role / Title','text',''],['team_department','Team / Department','text',''],['employment_type','Employment Type','select','Employee|Contractor|Intern|Leadership|Consultant'],['phone','Phone','text',''],['email','Email','email',''],['address_text','Address','textarea',''],['start_date','Start Date','date','']]),`<button class="btn" onclick="saveStaff()">Save Staff Record</button>`)}
window.saveStaff=async()=>{const f=formData('staffForm'),n=await SB.rpc('next_mtech_staff_no');if(n.error)return alert(n.error.message);f.staff_no=n.data;f.status='active';const {error}=await SB.from('staff').insert(f);if(error)return alert(error.message);closeModal();await loadAll(true)}
async function staffDocs(id){const s=state.staff.find(x=>x.id===id);const {data:docs}=await SB.from('staff_documents').select('*').eq('staff_id',id).order('created_at',{ascending:false});let list=(docs||[]).map(d=>`<div class="notice">${esc(d.title)} · ${esc(d.document_type)} <button class="btn alt small" onclick="openStaffDoc('${d.storage_path}')">Open</button></div>`).join('');modal('Staff Documents · '+esc(s.full_name),`${list||'<p class="muted">No documents uploaded yet.</p>'}<div class="field"><label>Document Title</label><input id="docTitle"></div><div class="field"><label>Type</label><select id="docType"><option>ID</option><option>CV</option><option>Certificate</option><option>Contract</option><option>Photo</option><option>Other</option></select></div><div class="field"><label>File</label><input id="docFile" type="file"></div><button class="btn" onclick="uploadStaffDoc('${id}')">Upload Document</button>`)}
window.uploadStaffDoc=async id=>{const f=$('docFile').files[0];if(!f)return alert('Choose a file.');const path=`${id}/${crypto.randomUUID()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await SB.storage.from('staff-files').upload(path,f);if(up.error)return alert(up.error.message);const ins=await SB.from('staff_documents').insert({staff_id:id,document_type:$('docType').value.toLowerCase(),title:$('docTitle').value||f.name,storage_path:path,file_name:f.name,mime_type:f.type,file_size:f.size});if(ins.error)return alert(ins.error.message);closeModal();await staffDocs(id)}
window.openStaffDoc=async path=>{const {data,error}=await SB.storage.from('staff-files').createSignedUrl(path,600);if(error)return alert(error.message);window.open(data.signedUrl,'_blank')}
function newAppointment(){modal('New Appointment',formHtml('apptForm',[['title','Title','text',''],['scheduled_at','Date & Time','datetime-local',''],['mode','Mode','select','On-Site|Remote|Customer Visit|Office Visit|Phone Call'],['location_text','Location','text',''],['notes','Notes','textarea','']]),`<button class="btn" onclick="saveAppointment()">Save Appointment</button>`)}
window.saveAppointment=async()=>{const f=formData('apptForm');f.scheduled_at=new Date(f.scheduled_at).toISOString();f.status='scheduled';await insertAndRefresh('appointments',f)}
function newReminder(){modal('New Reminder',formHtml('remForm',[['title','Title','text',''],['body','Details','textarea',''],['due_at','Due Date & Time','datetime-local','']]),`<button class="btn" onclick="saveReminder()">Save Reminder</button>`)}
window.saveReminder=async()=>{const f=formData('remForm');f.due_at=new Date(f.due_at).toISOString();f.status='pending';await insertAndRefresh('reminders',f)}
function newExpense(){modal('Add Expense',formHtml('expForm',[['expense_date','Date','date',new Date().toISOString().slice(0,10)],['category','Category','text',''],['description','Description','textarea',''],['currency','Currency','select','USD|LRD'],['amount','Amount','number','0'],['payment_method','Payment Method','text',''],['reference','Reference','text','']]),`<button class="btn" onclick="saveSimple('expenses','expForm')">Save Expense</button>`)}
function newAsset(){modal('Add Asset',formHtml('assetForm',[['name','Asset Name','text',''],['category','Category','text',''],['status','Status','select','active|maintenance|retired'],['assigned_to','Assigned To','text',''],['purchase_date','Purchase Date','date',''],['currency','Currency','select','USD|LRD'],['purchase_cost','Purchase Cost','number','0'],['serial_no','Serial No.','text',''],['notes','Notes','textarea','']]),`<button class="btn" onclick="saveAsset()">Save Asset</button>`)}
window.saveAsset=async()=>{const f=formData('assetForm'),n=await SB.rpc('next_mtech_asset_no');if(n.error)return alert(n.error.message);f.asset_no=n.data;await insertAndRefresh('assets',f)}
function editService(id){const s=id?state.services.find(x=>x.id===id):{};modal(id?'Edit Service':'Add Service',formHtml('svcForm',[['name','Service Name','text',s?.name||''],['description','Description','textarea',s?.description||''],['base_price_usd','Base Price USD','number',s?.base_price_usd??''],['base_price_lrd','Base Price LRD','number',s?.base_price_lrd??''],['warranty_days','Warranty Days','number',s?.warranty_days??''],['estimated_duration_text','Estimated Duration','text',s?.estimated_duration_text||''],['active','Active','select','true|false',String(s?.active??true)]]),`<button class="btn" onclick="saveService('${id||''}')">Save Service</button>`)}
window.saveService=async id=>{const f=formData('svcForm');['base_price_usd','base_price_lrd','warranty_days'].forEach(k=>{f[k]=f[k]===''?null:+f[k]});f.active=f.active==='true';let res=id?await SB.from('service_categories').update(f).eq('id',id):await SB.from('service_categories').insert(f);if(res.error)return alert(res.error.message);closeModal();await loadAll(true)}
function newSetting(){modal('Add / Update Setting',formHtml('setForm',[['key','Setting Key','text',''],['value','JSON Value','textarea','{}']]),`<button class="btn" onclick="saveSetting()">Save Setting</button>`)}
window.saveSetting=async()=>{const f=formData('setForm');let v;try{v=JSON.parse(f.value)}catch{return alert('Enter valid JSON, for example {"enabled":true}.')}const {error}=await SB.from('app_settings').upsert({key:f.key,value_json:v,updated_at:new Date().toISOString()});if(error)return alert(error.message);closeModal();await loadAll(true)}
window.saveSimple=async(t,f)=>{await insertAndRefresh(t,formData(f))}
async function insertAndRefresh(tableName,obj){const {error}=await SB.from(tableName).insert(obj);if(error)return alert(error.message);closeModal();await loadAll(true)}
function formData(id){const o={};document.querySelectorAll(`#${id} [name]`).forEach(x=>o[x.name]=x.value);return o}
function formHtml(id,fields){return `<div id="${id}">${fields.map(f=>{const [name,label,type,val,sel]=f;if(type==='textarea')return `<div class="field"><label>${label}</label><textarea name="${name}">${esc(val||'')}</textarea></div>`;if(type==='select'){const opts=String(val||'').split('|');const selected=sel??opts[0];return `<div class="field"><label>${label}</label><select name="${name}">${opts.map(o=>`<option ${String(o)===String(selected)?'selected':''}>${esc(o)}</option>`).join('')}</select></div>`}return `<div class="field"><label>${label}</label><input name="${name}" type="${type}" value="${esc(val||'')}"></div>`}).join('')}</div>`}
init();