// M-TECH Share Center v1.0
(function(){
 const BASE='https://johnsonmulbahe-oss.github.io/mtech-website/app/';
 const DEFAULTS={request_title:'M-TECH Technology Service Request',request_message:'Need reliable technology support? Send your service request directly to M-TECH using this secure form.',qr_title:'M-TECH QR Service Request',qr_message:'Scan or open this M-TECH link to request technology service.',document_message:'Please find your M-TECH document using this secure link.'};
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 let cfg={...DEFAULTS};
 function nav(){const n=document.getElementById('nav'),content=document.querySelector('.content');if(!n||!content||document.getElementById('shareCenter'))return;
   const b=document.createElement('button');b.className='navbtn';b.dataset.panel='shareCenter';b.textContent='Share Center';b.onclick=()=>{openPanel('shareCenter','Share Center');render()};n.appendChild(b);
   content.insertAdjacentHTML('beforeend',`<section id="shareCenter" class="panel"><div class="section-title"><div><h2>Share Center</h2><span class="muted">Share M-TECH public links without copying them manually</span></div><button class="btn alt small" onclick="mtechLoadShareSettings()">Refresh</button></div><div id="shareCards" class="grid2"></div><div class="card" style="margin-top:14px"><h3>CEO Sharing Settings</h3><p class="muted">Edit the wording that appears when you share M-TECH links. Changes apply to future shares.</p><div class="grid2"><div class="field"><label>Customer Request Share Title</label><input id="shareReqTitle"></div><div class="field"><label>QR Share Title</label><input id="shareQrTitle"></div></div><div class="field"><label>Customer Request Share Message</label><textarea id="shareReqMsg"></textarea></div><div class="field"><label>QR Share Message</label><textarea id="shareQrMsg"></textarea></div><div class="field"><label>Quotation / Invoice / Receipt Share Message</label><textarea id="shareDocMsg"></textarea></div><button class="btn" onclick="mtechSaveShareSettings()">Save Sharing Settings</button><span id="shareSaveMsg" class="muted" style="margin-left:8px"></span></div></section>`);
   const top=document.querySelector('.topbar .actions');if(top&&!document.getElementById('quickShareBtn')){const q=document.createElement('button');q.id='quickShareBtn';q.className='btn alt small';q.textContent='Share';q.onclick=()=>{openPanel('shareCenter','Share Center');render()};top.prepend(q)}
 }
 function cards(){return [
  {name:'Customer Request Form',desc:'Best link to share with customers who need M-TECH service.',url:BASE+'request-v7.html',title:cfg.request_title,msg:cfg.request_message},
  {name:'General M-TECH QR Page',desc:'Share or print the general M-TECH QR code.',url:BASE+'share-qr.html',title:cfg.qr_title,msg:cfg.qr_message},
  {name:'QR Distribution Register',desc:'CEO-only register for schools, churches, offices, communities and events.',url:BASE+'qr-distribution.html',title:'M-TECH QR Distribution Register',msg:'Open the M-TECH QR Distribution Register.'}
 ]}
 function render(){const root=document.getElementById('shareCards');if(!root)return;root.innerHTML=cards().map((x,i)=>`<div class="card"><h3>${esc(x.name)}</h3><p class="muted">${esc(x.desc)}</p><div class="field"><label>Link</label><input readonly value="${esc(x.url)}" onclick="this.select()"></div><div class="actions"><button class="btn small" onclick="mtechNativeShare(${i})">Share…</button><button class="btn alt small" onclick="mtechWhatsApp(${i})">WhatsApp</button><button class="btn alt small" onclick="mtechEmail(${i})">Email</button><button class="btn alt small" onclick="mtechSMS(${i})">SMS</button><button class="btn alt small" onclick="mtechFacebook(${i})">Facebook / Messenger</button><button class="btn alt small" onclick="mtechCopyShare(${i})">Copy Link</button></div></div>`).join('');
  const a=document.getElementById('shareReqTitle');if(a){a.value=cfg.request_title||'';document.getElementById('shareReqMsg').value=cfg.request_message||'';document.getElementById('shareQrTitle').value=cfg.qr_title||'';document.getElementById('shareQrMsg').value=cfg.qr_message||'';document.getElementById('shareDocMsg').value=cfg.document_message||''}
 }
 const item=i=>cards()[Number(i)];const text=x=>(x.msg?x.msg+'\n\n':'')+x.url;
 window.mtechNativeShare=async i=>{const x=item(i);if(navigator.share){try{await navigator.share({title:x.title,text:x.msg,url:x.url});return}catch(e){if(e.name==='AbortError')return}}window.mtechCopyShare(i)};
 window.mtechWhatsApp=i=>{const x=item(i);location.href='https://wa.me/?text='+encodeURIComponent(text(x))};
 window.mtechEmail=i=>{const x=item(i);location.href='mailto:?subject='+encodeURIComponent(x.title)+'&body='+encodeURIComponent(text(x))};
 window.mtechSMS=i=>{const x=item(i);location.href='sms:?&body='+encodeURIComponent(text(x))};
 window.mtechFacebook=i=>{const x=item(i);const share='https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(x.url)+'&quote='+encodeURIComponent(x.msg||'');window.open(share,'_blank','noopener')};
 window.mtechCopyShare=async i=>{const x=item(i);try{await navigator.clipboard.writeText(x.url);alert('M-TECH link copied.')}catch{prompt('Copy this M-TECH link:',x.url)}};
 window.mtechShareUrl=async function(url,title,msg){const data={title:title||'M-TECH',text:msg||cfg.document_message,url};if(navigator.share){try{await navigator.share(data);return}catch(e){if(e.name==='AbortError')return}}try{await navigator.clipboard.writeText(url);alert('Link copied.')}catch{prompt('Copy this link:',url)}};
 window.mtechLoadShareSettings=async function(){try{const {data,error}=await SB.from('app_settings').select('value_json').eq('key','sharing').maybeSingle();if(!error&&data?.value_json)cfg={...DEFAULTS,...data.value_json}}catch{}render()};
 window.mtechSaveShareSettings=async function(){const value_json={request_title:document.getElementById('shareReqTitle').value.trim()||DEFAULTS.request_title,request_message:document.getElementById('shareReqMsg').value.trim()||DEFAULTS.request_message,qr_title:document.getElementById('shareQrTitle').value.trim()||DEFAULTS.qr_title,qr_message:document.getElementById('shareQrMsg').value.trim()||DEFAULTS.qr_message,document_message:document.getElementById('shareDocMsg').value.trim()||DEFAULTS.document_message};const m=document.getElementById('shareSaveMsg');m.textContent='Saving…';const {error}=await SB.from('app_settings').upsert({key:'sharing',value_json,updated_at:new Date().toISOString()},{onConflict:'key'});if(error){m.textContent=error.message;return}cfg={...value_json};m.textContent='Saved.';render()};
 async function init(){nav();await window.mtechLoadShareSettings()}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();