// M-TECH public website and core module shortcuts; public website URL is read from editable company_profile settings.
(function(){
 const FALLBACK=location.origin+'/';
 if(!document.querySelector('script[data-mtech-terms-gate]')){const s=document.createElement('script');s.src='terms-gate.js?v=42';s.defer=true;s.dataset.mtechTermsGate='1';document.head.appendChild(s)}
 if(!document.querySelector('script[data-mtech-module-consent]')){const s=document.createElement('script');s.src='module-consent-gate.js?v=44';s.defer=true;s.dataset.mtechModuleConsent='1';document.head.appendChild(s)}
 if(!document.querySelector('script[data-mtech-compliance-notify]')){const s=document.createElement('script');s.src='compliance-notifications.js?v=45';s.defer=true;s.dataset.mtechComplianceNotify='1';document.head.appendChild(s)}
 async function getUrl(){try{if(globalThis.SB){const {data}=await SB.from('app_settings').select('value_json').eq('key','company_profile').maybeSingle();const u=data?.value_json?.website_url;if(u&&/^https?:\/\//i.test(u))return u}}catch(_){}return FALLBACK}
 function addNav(nav,id,label,href){if(nav&&!document.getElementById(id)){const a=document.createElement('a');a.id=id;a.className='navbtn';a.href=href;a.textContent=label;nav.appendChild(a)}}
 function addTop(actions,id,label,href){if(actions&&!document.getElementById(id)){const a=document.createElement('a');a.id=id;a.className='btn alt small';a.href=href;a.textContent=label;actions.appendChild(a)}}
 async function install(){const url=await getUrl();const nav=document.getElementById('nav');if(nav&&!document.getElementById('mtechWebsiteNav')){const a=document.createElement('a');a.id='mtechWebsiteNav';a.className='navbtn';a.href=url;a.target='_blank';a.rel='noopener';a.textContent='M-TECH Website';nav.appendChild(a)}
   addNav(nav,'mtechMarketplaceNav','Technology Marketplace','marketplace.html');addNav(nav,'mtechStoreGuideNav','Store Setup Guide','marketplace-store-guide.html');addNav(nav,'mtechMarketplaceRulesNav','Marketplace Rules','marketplace-rules.html');addNav(nav,'mtechTermsCenterNav','Terms & Conditions','terms-center.html');addNav(nav,'mtechPrivacyNav','Privacy Policy','terms-center.html?doc=privacy_policy');addNav(nav,'mtechBuyerProtectionNav','Buyer Protection','buyer-protection.html');addNav(nav,'mtechTrustCenterNav','Trust & Assurance Center','trust-center.html');addNav(nav,'mtechComplianceNav','CEO Compliance Center','compliance-center.html');addNav(nav,'mtechSponsorsNavLite','Sponsors & Partners','sponsors-partners.html');
   const actions=document.querySelector('.topbar .actions');if(actions&&!document.getElementById('mtechWebsiteTop')){const a=document.createElement('a');a.id='mtechWebsiteTop';a.className='btn alt small';a.href=url;a.target='_blank';a.rel='noopener';a.textContent='Website';actions.appendChild(a)}addTop(actions,'mtechMarketplaceTopLite','Marketplace','marketplace.html');addTop(actions,'mtechTrustTopLite','Trust & Safety','trust-center.html');addTop(actions,'mtechTermsTopLite','Terms','terms-center.html');addTop(actions,'mtechComplianceTopLite','Compliance','compliance-center.html')}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();