const enc=new TextEncoder();
const ITER=100000;
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}})}
function hex(b){return [...b].map(x=>x.toString(16).padStart(2,'0')).join('')}
function unhex(s){if(!/^[0-9a-f]+$/i.test(s)||s.length%2)return null;let a=new Uint8Array(s.length/2);for(let i=0;i<a.length;i++)a[i]=parseInt(s.slice(i*2,i*2+2),16);return a}
async function hashPassword(p,salt=crypto.getRandomValues(new Uint8Array(16))){let k=await crypto.subtle.importKey('raw',enc.encode(p),'PBKDF2',false,['deriveBits']);let bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations:ITER},k,256);return `pbkdf2_sha256$${ITER}$${hex(salt)}$${hex(new Uint8Array(bits))}`}
async function verify(p,h){let q=String(h||'').split('$');if(q.length!==4||q[0]!=='pbkdf2_sha256')return false;let salt=unhex(q[2]),exp=unhex(q[3]),n=+q[1];if(!salt||!exp||n<1||n>100000)return false;let k=await crypto.subtle.importKey('raw',enc.encode(p),'PBKDF2',false,['deriveBits']);let bits=new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations:n},k,exp.length*8));let d=0;for(let i=0;i<exp.length;i++)d|=bits[i]^exp[i];return d===0}
async function sha(v){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(v))))}
function cookie(req,name){let m=(req.headers.get('cookie')||'').match(new RegExp('(?:^|;\\s*)'+name+'=([^;]+)'));return m?m[1]:''}
async function init(db){await db.prepare(`CREATE TABLE IF NOT EXISTS member_users(id INTEGER PRIMARY KEY AUTOINCREMENT,full_name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,is_active INTEGER NOT NULL DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP,last_login TEXT)`).run();await db.prepare(`CREATE TABLE IF NOT EXISTS member_sessions(id INTEGER PRIMARY KEY AUTOINCREMENT,member_id INTEGER NOT NULL,token_hash TEXT NOT NULL UNIQUE,expires_at TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`).run();await db.prepare(`CREATE TABLE IF NOT EXISTS member_progress(id INTEGER PRIMARY KEY AUTOINCREMENT,member_id INTEGER NOT NULL,item_key TEXT NOT NULL,completed INTEGER NOT NULL DEFAULT 1,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(member_id,item_key))`).run();await db.prepare(`CREATE TABLE IF NOT EXISTS quiz_attempts(id INTEGER PRIMARY KEY AUTOINCREMENT,member_id INTEGER NOT NULL,quiz_key TEXT NOT NULL,score INTEGER NOT NULL,total INTEGER NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`).run()}
async function user(req,db){let t=cookie(req,'mtech_member_session');if(!t)return null;let h=await sha(t);return db.prepare(`SELECT u.id,u.full_name,u.email FROM member_sessions s JOIN member_users u ON u.id=s.member_id WHERE s.token_hash=? AND s.expires_at>CURRENT_TIMESTAMP AND u.is_active=1 LIMIT 1`).bind(h).first()}
function token(){return hex(crypto.getRandomValues(new Uint8Array(32)))}
export async function onRequest({request,env}){if(!env.DB)return json({ok:false,error:'Database unavailable.'},500);await init(env.DB);let url=new URL(request.url),action=url.searchParams.get('action')||'';
if(request.method==='POST'&&action==='register'){let b=await request.json().catch(()=>null);if(!b)return json({ok:false,error:'Invalid request.'},400);let name=String(b.fullName||'').trim(),email=String(b.email||'').trim().toLowerCase(),p=String(b.password||'');if(name.length<2||!/^\S+@\S+\.\S+$/.test(email)||p.length<8)return json({ok:false,error:'Enter your name, a valid email, and a password of at least 8 characters.'},400);let exists=await env.DB.prepare('SELECT id FROM member_users WHERE lower(email)=?').bind(email).first();if(exists)return json({ok:false,error:'An account already exists for this email.'},409);let h=await hashPassword(p);let r=await env.DB.prepare('INSERT INTO member_users(full_name,email,password_hash) VALUES(?,?,?)').bind(name,email,h).run();return json({ok:true,message:'Account created. You can now sign in.'},201)}
if(request.method==='POST'&&action==='login'){let b=await request.json().catch(()=>null),email=String(b?.email||'').trim().toLowerCase(),p=String(b?.password||'');let u=await env.DB.prepare('SELECT * FROM member_users WHERE lower(email)=? LIMIT 1').bind(email).first();if(!u||!u.is_active||!(await verify(p,u.password_hash)))return json({ok:false,error:'Invalid email or password.'},401);let t=token(),h=await sha(t);await env.DB.prepare("DELETE FROM member_sessions WHERE expires_at<=CURRENT_TIMESTAMP").run();await env.DB.prepare("INSERT INTO member_sessions(member_id,token_hash,expires_at) VALUES(?,?,datetime('now','+7 days'))").bind(u.id,h).run();await env.DB.prepare('UPDATE member_users SET last_login=CURRENT_TIMESTAMP WHERE id=?').bind(u.id).run();return json({ok:true,user:{id:u.id,fullName:u.full_name,email:u.email}},200,{'set-cookie':`mtech_member_session=${t}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=604800`})}
if(request.method==='POST'&&action==='logout'){let t=cookie(request,'mtech_member_session');if(t)await env.DB.prepare('DELETE FROM member_sessions WHERE token_hash=?').bind(await sha(t)).run();return json({ok:true},200,{'set-cookie':'mtech_member_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0'})}
let u=await user(request,env.DB);if(!u)return json({ok:false,error:'Sign in required.'},401);
if(request.method==='GET'&&action==='session'){let p=await env.DB.prepare('SELECT item_key,completed FROM member_progress WHERE member_id=?').bind(u.id).all();let q=await env.DB.prepare('SELECT quiz_key,MAX(score) best_score,total FROM quiz_attempts WHERE member_id=? GROUP BY quiz_key').bind(u.id).all();return json({ok:true,user:{id:u.id,fullName:u.full_name,email:u.email},progress:p.results||[],quizzes:q.results||[]})}
if(request.method==='POST'&&action==='progress'){let b=await request.json().catch(()=>null),key=String(b?.itemKey||'').slice(0,80);if(!key)return json({ok:false,error:'Missing lesson.'},400);await env.DB.prepare(`INSERT INTO member_progress(member_id,item_key,completed,updated_at) VALUES(?,?,1,CURRENT_TIMESTAMP) ON CONFLICT(member_id,item_key) DO UPDATE SET completed=1,updated_at=CURRENT_TIMESTAMP`).bind(u.id,key).run();return json({ok:true})}
if(request.method==='POST'&&action==='quiz'){let b=await request.json().catch(()=>null),key=String(b?.quizKey||'').slice(0,80),score=+b?.score,total=+b?.total;if(!key||!Number.isInteger(score)||!Number.isInteger(total)||score<0||total<1||score>total)return json({ok:false,error:'Invalid quiz result.'},400);await env.DB.prepare('INSERT INTO quiz_attempts(member_id,quiz_key,score,total) VALUES(?,?,?,?)').bind(u.id,key,score,total).run();return json({ok:true})}
return json({ok:false,error:'Not found.'},404)}